/**
 * Screenshot manifest — the single source of truth for every image the docs
 * reference.
 *
 * Two consumers read this file, which is why it exists at all:
 *
 *   1. `<Screenshot id="…" />` (components/ui/screenshot.tsx) renders the
 *      image when the file is present under `public/screenshots/`, and a
 *      placeholder carrying `what` + `state` when it is not.
 *   2. `scripts/build-screenshot-index.mjs` emits `docs/screenshot-index.xlsx`
 *      — the capture worklist.
 *
 * Every entry here has its file on disk: the Playwright suite fails on a
 * referenced screenshot without a file, so a page never ships with a
 * "Screenshot pending" placeholder. The set was recaptured on 2026-09-28 from
 * the application itself (its own render, 2× scale, 1400 × 900 window) on
 * the bundled sample site, a three-plot variant of it, and a test module and
 * inverter file — see docs/superpowers/plans/2026-09-21-desktop-docs-revamp.md.
 *
 * SolarLayout Desktop has a single visual theme, so there is exactly ONE
 * image per entry — no light/dark pairs.
 *
 * `priority` records how essential the image is to its page:
 *   1 — essential; the page does not make sense without it
 *   2 — valuable; explains something the prose can only describe
 *   3 — nice to have; polish
 */
export interface ScreenshotSpec {
  /** Stable id used in MDX: `<Screenshot id="…" />`. */
  id: string
  /** Path under `public/screenshots/`. */
  file: string
  /** Docs page that uses it, for the capture worklist. */
  page: string
  /** Short human title — the caption and the worklist row title. */
  title: string
  /** Alt text. Describes the content, not the act of screenshotting. */
  alt: string
  /** What the frame must contain. */
  what: string
  /** How to get the app into that state before capturing. */
  state: string
  /** Callouts to add after capture. Empty string when none. */
  annotations: string
  priority: 1 | 2 | 3
}

export const SCREENSHOTS: ScreenshotSpec[] = [
  {
    id: "new-design",
    file: "start/new-design.png",
    page: "/docs/design-modes",
    title: "The New design window",
    alt: "The SolarLayout · New design window with the MOUNTING and INVERTER segmented controls, the summary card reading Fixed tilt + string inverters, and the Continue button.",
    what: "The whole New design window at launch: both segmented controls, the summary card and Continue.",
    state: "Launch the application. The window is the first thing shown.",
    annotations: "",
    priority: 1,
  },
  {
    id: "new-design-tracker-central",
    file: "start/new-design-tracker-central.png",
    page: "/docs/design-modes",
    title: "Tracker with a central inverter selected",
    alt: "The New design window with Single-axis tracker and Central inverter selected and the summary card updated to match.",
    what: "The same window with the other two options chosen, so the card reads Single-axis tracker + central inverter.",
    state: "Click Single-axis tracker and Central inverter before Continue.",
    annotations: "",
    priority: 2,
  },
  {
    id: "main-window-empty",
    file: "start/main-window-empty.png",
    page: "/docs/workspace/main-window",
    title: "The main window before a layout",
    alt: "The main window in a fixed-tilt string-inverter design: the ribbon, the pinned Generate Layout button with its hint, the Site tab of the inputs, the view tabs and an empty plot.",
    what: "The whole window straight after Continue: ribbon, disabled Generate Layout with the hint line, the five stage tabs on Site, the view header and the empty plot.",
    state: "Choose Fixed tilt + String inverter and capture before loading any file.",
    annotations: "",
    priority: 1,
  },
  {
    id: "ribbon",
    file: "start/ribbon.png",
    page: "/docs/workspace/main-window",
    title: "The ribbon",
    alt: "The navy ribbon with the SolarLayout brand, the design chip, the access chip, and the Docs and Support buttons.",
    what: "The ribbon only, wide enough to read every item.",
    state: "Any window; the access chip shows this device's status.",
    annotations: "",
    priority: 1,
  },
  {
    id: "generate-hint",
    file: "start/generate-hint.png",
    page: "/docs/first-layout",
    title: "Generate Layout and its hint",
    alt: "The pinned Generate Layout button, greyed out, with the hint Select a boundary file on the Site tab to generate a layout.",
    what: "The pinned header: the disabled button and the hint line under it.",
    state: "Before any boundary file is selected.",
    annotations: "",
    priority: 1,
  },
  {
    id: "site-loaded",
    file: "start/site-loaded.png",
    page: "/docs/first-layout",
    title: "The sample site loaded",
    alt: "The main window with the sample site loaded: the boundary, pond, transmission line and obstruction drawn on the plot, Generate Layout enabled.",
    what: "The whole window after Open sample site: the boundary preview on the plot and the enabled Generate Layout button.",
    state: "Click Open sample site on the Site tab.",
    annotations: "",
    priority: 1,
  },
  {
    id: "tab-array-window",
    file: "start/tab-array.png",
    page: "/docs/workspace/main-window",
    title: "The Array tab",
    alt: "The main window showing the Array tab: the MOUNTING chip, Module Specifications and MMS-Table Configuration.",
    what: "The window with the Array tab selected.",
    state: "Click Array.",
    annotations: "",
    priority: 2,
  },
  {
    id: "tab-electrical-window",
    file: "start/tab-electrical.png",
    page: "/docs/workspace/main-window",
    title: "The Electrical tab",
    alt: "The main window on the Electrical tab: the String Inverter card, the ACCB & Transformer card and the Cables card.",
    what: "The window with the Electrical tab selected.",
    state: "Click Electrical.",
    annotations: "",
    priority: 2,
  },
  {
    id: "tab-yield-window",
    file: "start/tab-yield.png",
    page: "/docs/workspace/main-window",
    title: "The Yield tab",
    alt: "The main window showing the Yield tab: Run Energy Calculation and Energy Yield.",
    what: "The window with the Yield tab selected.",
    state: "Click Yield.",
    annotations: "",
    priority: 2,
  },
  {
    id: "tab-tools-locked",
    file: "start/tab-tools-locked.png",
    page: "/docs/workspace/main-window",
    title: "The Tools tab before a layout",
    alt: "The main window on the Tools tab before a layout: every button greyed out except Robot count from DXF…, which needs no layout.",
    what: "The window with the Tools tab selected before a layout.",
    state: "Click Tools before generating.",
    annotations: "",
    priority: 2,
  },
  {
    id: "tab-tools",
    file: "start/tab-tools.png",
    page: "/docs/workspace/main-window",
    title: "The Tools tab after a layout",
    alt: "The main window on the Tools tab after a layout: the Obstructions card, the ICR tip, Main Control Room & Objects and the five Studies buttons, with the placed MCR's hint.",
    what: "The window with the Tools tab selected after a layout.",
    state: "Generate, then click Tools.",
    annotations: "",
    priority: 1,
  },
  {
    id: "main-window-tracker-central",
    file: "start/main-window-tracker-central.png",
    page: "/docs/design-modes",
    title: "A tracker, central-inverter window",
    alt: "The main window in a single-axis tracker, central-inverter design; the design chip reads Tracker · Central inverter.",
    what: "The whole empty window in that design, so the chip and the Site tab are visible.",
    state: "Choose Single-axis tracker + Central inverter at launch.",
    annotations: "",
    priority: 2,
  },
  {
    id: "multi-plot-loaded",
    file: "start/multi-plot-loaded.png",
    page: "/docs/layout/multi-plot",
    title: "A three-plot file loaded",
    alt: "The main window with a file of three boundaries loaded and previewed; the summary line under the file field reads 3 boundaries.",
    what: "The whole window after loading a multi-boundary file, before generating.",
    state: "Browse to a file containing three boundaries.",
    annotations: "",
    priority: 2,
  },
  {
    id: "boundary-file-card",
    file: "inputs/boundary-file-card.png",
    page: "/docs/inputs/boundary-files",
    title: "The Input Boundary File card",
    alt: "The Input Boundary File card with the empty path field, the Browse button, the info button, the supported-formats line and the Open sample site link.",
    what: "The card only, before a file is chosen.",
    state: "Site tab, nothing loaded.",
    annotations: "",
    priority: 1,
  },
  {
    id: "boundary-file-loaded",
    file: "inputs/boundary-file-loaded.png",
    page: "/docs/inputs/boundary-files",
    title: "After a file is read",
    alt: "The Input Boundary File card with sample-demo.kmz in the field and the summary line 1 boundary · 1 obstacle · 1 line obstruction.",
    what: "The card after a file has been read, showing the summary line.",
    state: "Load the sample site.",
    annotations: "",
    priority: 1,
  },
  {
    id: "boundary-guide",
    file: "inputs/boundary-guide.png",
    page: "/docs/inputs/kmz-requirements",
    title: "The KMZ File Preparation Guide",
    alt: "The KMZ File Preparation Guide window with its numbered sections and the quick-reference table.",
    what: "The guide window opened by the info button.",
    state: "Click the info button beside Browse.",
    annotations: "",
    priority: 1,
  },
  {
    id: "boundary-validation",
    file: "inputs/boundary-validation.png",
    page: "/docs/inputs/kmz-requirements",
    title: "The Check boundaries window",
    alt: "The Check boundaries window: a banner reading 2 of 4 boundaries have a problem, a table with Leave out ticked for each open ring, and the Continue without 2 button.",
    what: "The window as shown for a file with two open rings.",
    state: "Load a file containing boundaries whose rings are not closed.",
    annotations: "",
    priority: 1,
  },
  {
    id: "dxf-site-coordinates",
    file: "inputs/dxf-site-coordinates.png",
    page: "/docs/inputs/cad-boundary",
    title: "Site reference for a CAD drawing",
    alt: "The Site reference window for a drawing in local coordinates: Place by latitude and longitude chosen, latitude and longitude filled in, the Placed by hand banner and the Place the drawing here button.",
    what: "The window for a local-coordinate .dxf with a latitude and longitude typed in.",
    state: "Browse to a .dxf drawn in local coordinates and type the site centre's latitude and longitude.",
    annotations: "",
    priority: 1,
  },
  {
    id: "image-scale",
    file: "inputs/image-scale.png",
    page: "/docs/inputs/image-boundary",
    title: "Site reference for an image",
    alt: "The Site reference window for an image: the SCALE card reading 100.00 m on site is drawn as 10.00 mm, then the LOCATION card with nothing filled in.",
    what: "The window as it opens for an image file, scale card included.",
    state: "Browse to an image file.",
    annotations: "",
    priority: 1,
  },
  {
    id: "tab-site",
    file: "inputs/tab-site.png",
    page: "/docs/inputs/site",
    title: "The Site tab, top to bottom",
    alt: "The Site tab's four cards in one tall image: Input Boundary File, Site Parameters, Structures & Shadow (keep-clear) and Topography (slope-aware exclusion).",
    what: "The full Site tab at its default values, unscrolled.",
    state: "Site tab, nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },
  {
    id: "tab-array",
    file: "inputs/tab-array.png",
    page: "/docs/inputs/module",
    title: "The Array tab, top to bottom",
    alt: "The Array tab's cards in one tall image: the MOUNTING chip, Module Specifications, MMS-Table Configuration and Spacing & Tilt.",
    what: "The full Array tab at its default values in a fixed-tilt design.",
    state: "Array tab, nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },
  {
    id: "tab-yield",
    file: "inputs/tab-yield.png",
    page: "/docs/energy/overview",
    title: "The Yield tab, top to bottom",
    alt: "The Yield tab in one tall image: the Run Energy Calculation card and the Energy Yield card with its ADVANCED expanders closed.",
    what: "The full Yield tab at its default values.",
    state: "Yield tab, nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },
  {
    id: "tab-yield-advanced-open",
    file: "inputs/tab-yield-advanced-open.png",
    page: "/docs/energy/losses",
    title: "The Yield tab with ADVANCED open",
    alt: "The Yield tab with the Performance-ratio losses, Degradation & lifetime and Uncertainty & exceedance expanders open.",
    what: "The full Yield tab with all three expanders open.",
    state: "Click each expander header.",
    annotations: "",
    priority: 2,
  },
  {
    id: "module-group",
    file: "inputs/module-group.png",
    page: "/docs/inputs/module",
    title: "Module Specifications",
    alt: "The Module Specifications card at its defaults: no .PAN file loaded, length, width, wattage, and the bifacial options with the factor greyed out.",
    what: "The card only, at its defaults.",
    state: "Array tab, no module file loaded.",
    annotations: "",
    priority: 1,
  },
  {
    id: "module-pan-loaded",
    file: "inputs/module-pan-loaded.png",
    page: "/docs/inputs/module",
    title: "After loading a module file",
    alt: "The Module Specifications card after a bifacial module file is loaded: the module name on the file row, the dimensions and wattage filled in, Bifacial ticked and the factor filled in.",
    what: "The same card after Load .PAN with a bifacial module.",
    state: "Click Load .PAN and pick a bifacial module file.",
    annotations: "",
    priority: 1,
  },
  {
    id: "pan-viewer",
    file: "inputs/pan-viewer.png",
    page: "/docs/inputs/module",
    title: "The module file viewer",
    alt: "The Module (PAN) viewer on its Basic data tab with the tab strip visible.",
    what: "The viewer on its first tab.",
    state: "Load a module file, then click View.",
    annotations: "",
    priority: 2,
  },
  {
    id: "pan-viewer-graphs",
    file: "inputs/pan-viewer-graphs.png",
    page: "/docs/inputs/module",
    title: "The module's current and power curves",
    alt: "The Graphs tab of the module file viewer with the I–V and P–V curves at STC.",
    what: "The Graphs tab with both curves drawn.",
    state: "In the viewer, open the Graphs tab.",
    annotations: "",
    priority: 2,
  },
  {
    id: "string-sizing",
    file: "inputs/string-sizing.png",
    page: "/docs/inputs/string-sizing",
    title: "The String sizing window",
    alt: "The String sizing window: SITE and CELL TEMPERATURE inputs on the left; on the right a green verdict 13 to 27 modules in series are feasible, the range bar, the modules-in-series and parallel-strings fields, two voltage tiles, and the Use 27 in series × 2 strings button.",
    what: "The window with a module and an inverter file loaded and a feasible range showing.",
    state: "Load a .PAN and a .OND file, then click Size… beside Modules per row.",
    annotations: "",
    priority: 1,
  },
  {
    id: "table-group",
    file: "inputs/table-group.png",
    page: "/docs/inputs/table",
    title: "MMS-Table Configuration",
    alt: "The MMS-Table Configuration card at its defaults, with the Size… button beside Modules per row and the two placement options.",
    what: "The card only, at its defaults.",
    state: "Array tab in a fixed-tilt design.",
    annotations: "",
    priority: 1,
  },
  {
    id: "tracker-group",
    file: "inputs/tracker-group.png",
    page: "/docs/inputs/tracker",
    title: "Tracker Configuration",
    alt: "The Tracker Configuration card at its defaults with its three sections and the green live preview line of aperture, length, GCR and modules per tracker.",
    what: "The card only, at its defaults, including the preview line.",
    state: "Array tab in a tracker design.",
    annotations: "",
    priority: 1,
  },
  {
    id: "spacing-tilt-group",
    file: "inputs/spacing-tilt-group.png",
    page: "/docs/inputs/spacing-and-tilt",
    title: "Spacing & Tilt before a layout",
    alt: "The Spacing & Tilt card with both override boxes unticked, both value fields greyed out, and the Auto labels showing.",
    what: "The card before Generate Layout has run.",
    state: "Array tab, before generating.",
    annotations: "",
    priority: 1,
  },
  {
    id: "spacing-tilt-auto-resolved",
    file: "inputs/spacing-tilt-auto-resolved.png",
    page: "/docs/inputs/spacing-and-tilt",
    title: "Automatic tilt and pitch after a layout",
    alt: "The Spacing & Tilt card after a layout, with the Auto labels reporting the derived tilt and pitch and the values pre-filled into the greyed-out fields.",
    what: "The same card after Generate Layout, both overrides still off.",
    state: "Generate a layout, then look at the card.",
    annotations: "",
    priority: 1,
  },
  {
    id: "site-parameters",
    file: "inputs/site-parameters.png",
    page: "/docs/inputs/site",
    title: "Site Parameters",
    alt: "The Site Parameters card at its defaults: perimeter road width, Place Lightning Arresters unticked with the radius greyed out, ICR Block and the transmission line corridor.",
    what: "The card only, at its defaults.",
    state: "Site tab, nothing changed.",
    annotations: "",
    priority: 1,
  },
  {
    id: "site-parameters-la-on",
    file: "inputs/site-parameters-la-on.png",
    page: "/docs/layout/lightning-arresters",
    title: "Lightning arresters switched on",
    alt: "The Site Parameters card with Place Lightning Arresters ticked and the LA protection radius enabled at 100 m.",
    what: "The card with the arrester option on.",
    state: "Tick Place Lightning Arresters.",
    annotations: "",
    priority: 2,
  },
  {
    id: "structures-shadow",
    file: "inputs/structures-shadow.png",
    page: "/docs/inputs/structures-and-shadow",
    title: "Structures & Shadow (keep-clear)",
    alt: "The Structures & Shadow card: the L, W and H columns for ICR, MCR, USS and Object, the LA row, the shadow window, the clear-tables tick, and the street light rows.",
    what: "The whole card at its defaults.",
    state: "Site tab, nothing changed.",
    annotations: "",
    priority: 1,
  },
  {
    id: "topography",
    file: "inputs/topography.png",
    page: "/docs/inputs/topography",
    title: "Topography",
    alt: "The Topography card at its defaults with Avoid steep ground unticked, the contour data row reading Auto (satellite DEM), the slope limits and the depression option.",
    what: "The whole card at its defaults.",
    state: "Site tab, nothing changed.",
    annotations: "",
    priority: 1,
  },
  {
    id: "topography-enabled",
    file: "inputs/topography-enabled.png",
    page: "/docs/inputs/topography",
    title: "Topography enabled",
    alt: "The Topography card with Avoid steep ground ticked.",
    what: "The card with the terrain check switched on.",
    state: "Tick Avoid steep ground.",
    annotations: "",
    priority: 2,
  },
  {
    id: "inverter-group-string",
    file: "inputs/inverter-group-string.png",
    page: "/docs/inputs/inverter",
    title: "The String Inverter card",
    alt: "The String Inverter card at its defaults: maximum strings per inverter and the OND file row with Load .OND and View.",
    what: "The card only, no inverter file loaded.",
    state: "Electrical tab in a string-inverter design.",
    annotations: "",
    priority: 1,
  },
  {
    id: "inverter-group-central",
    file: "inputs/inverter-group-central.png",
    page: "/docs/inputs/inverter",
    title: "The SMB card in a central-inverter design",
    alt: "The SMB – String Monitoring Box card with maximum strings per SMB and the extra Max SMB per Central Inverter field.",
    what: "The same card in a central-inverter design, showing the extra field.",
    state: "Electrical tab in a central-inverter design.",
    annotations: "",
    priority: 1,
  },
  {
    id: "ond-loaded",
    file: "inputs/ond-loaded.png",
    page: "/docs/inputs/inverter",
    title: "Inverter file loaded",
    alt: "The String Inverter card after an inverter file is loaded, with the make and model on the row and View enabled.",
    what: "The card after Load .OND.",
    state: "Click Load .OND and pick an inverter file.",
    annotations: "",
    priority: 2,
  },
  {
    id: "ond-viewer",
    file: "inputs/ond-viewer.png",
    page: "/docs/inputs/inverter",
    title: "The inverter file viewer",
    alt: "The Inverter (OND) viewer on its Main parameters tab with the tab strip visible.",
    what: "The viewer on its first tab.",
    state: "Load an inverter file, then click View.",
    annotations: "",
    priority: 2,
  },
  {
    id: "ond-efficiency-curve",
    file: "inputs/ond-efficiency-curve.png",
    page: "/docs/inputs/inverter",
    title: "The inverter efficiency curve",
    alt: "The Efficiency curve tab of the inverter file viewer.",
    what: "The curve tab with the curve drawn.",
    state: "In the viewer, open Efficiency curve.",
    annotations: "",
    priority: 2,
  },
  {
    id: "cables-group",
    file: "inputs/cables-group.png",
    page: "/docs/inputs/cables",
    title: "The Cables card",
    alt: "The Cables card at its defaults: Calculate cables unticked, inter-module lead 0.00 m/module, the string return run unticked, and DC cable slack 10.0 %.",
    what: "The card only, at its defaults.",
    state: "Electrical tab, nothing changed.",
    annotations: "",
    priority: 1,
  },
  {
    id: "cables-group-on",
    file: "inputs/cables-group-on.png",
    page: "/docs/inputs/cables",
    title: "Cable calculation switched on",
    alt: "The Cables card with Calculate cables ticked.",
    what: "The card with the option on.",
    state: "Tick Calculate cables and choose Enable Now.",
    annotations: "",
    priority: 2,
  },
  {
    id: "cables-group-central",
    file: "inputs/cables-group-central.png",
    page: "/docs/inputs/cables",
    title: "The Cables card in a central-inverter design",
    alt: "The Cables card in a central-inverter design.",
    what: "The card in that design.",
    state: "Electrical tab in a central-inverter design.",
    annotations: "",
    priority: 2,
  },
  {
    id: "cable-calc-notice",
    file: "inputs/cable-calc-notice.png",
    page: "/docs/inputs/cables",
    title: "The performance notice",
    alt: "The Cable Calculation — Performance Notice with its text and the Enable Now and Not Now (Recommended) buttons.",
    what: "The notice as it appears when Calculate cables is ticked.",
    state: "Tick Calculate cables.",
    annotations: "",
    priority: 1,
  },
  {
    id: "run-section",
    file: "energy/run-section.png",
    page: "/docs/energy/overview",
    title: "Run Energy Calculation before a layout",
    alt: "The Run Energy Calculation card with Calculate Energy, Show Energy Chart, the Interval selector and Export TMY data CSV all greyed out.",
    what: "The card before a layout exists.",
    state: "Yield tab, before generating.",
    annotations: "",
    priority: 1,
  },
  {
    id: "run-section-done",
    file: "energy/run-section-done.png",
    page: "/docs/energy/overview",
    title: "After an energy run",
    alt: "The Run Energy Calculation card after a run, its status line reporting PR, year-one energy, CUF and the lifetime total.",
    what: "The card after Calculate Energy has finished.",
    state: "Generate, then click Calculate Energy.",
    annotations: "",
    priority: 1,
  },
  {
    id: "yield-group",
    file: "energy/yield-group.png",
    page: "/docs/energy/weather",
    title: "The Energy Yield card",
    alt: "The Energy Yield card at its defaults: the weather source ticks with PVGIS selected, the irradiance fields, ambient temperature, mounting type, wind speed, albedo, and the three ADVANCED expanders closed.",
    what: "The whole card at its defaults.",
    state: "Yield tab, nothing changed.",
    annotations: "",
    priority: 1,
  },
  {
    id: "weather-source-file",
    file: "energy/weather-source-file.png",
    page: "/docs/energy/weather",
    title: "The hourly file source selected",
    alt: "The Energy Yield card with Hourly GHI file (CSV) ticked and the GHI file row with its Browse button revealed.",
    what: "The card with the file source selected.",
    state: "Tick Hourly GHI file (CSV).",
    annotations: "",
    priority: 2,
  },
  {
    id: "ghi-file-format",
    file: "energy/ghi-file-format.png",
    page: "/docs/energy/weather",
    title: "The hourly file format reminder",
    alt: "The Hourly GHI File — Required Format reminder listing the three columns: timestamp, GHI and ambient temperature.",
    what: "The reminder as it appears.",
    state: "Tick Hourly GHI file (CSV).",
    annotations: "",
    priority: 1,
  },
  {
    id: "irradiance-fetched",
    file: "energy/irradiance-fetched.png",
    page: "/docs/energy/weather",
    title: "Irradiance after an automatic fetch",
    alt: "The Energy Yield card after Calculate Energy: GHI and GTI filled in and the green source line naming the service.",
    what: "The card after a fetch, source line visible.",
    state: "With the automatic source selected, generate and click Calculate Energy.",
    annotations: "",
    priority: 1,
  },
  {
    id: "losses-expander",
    file: "energy/losses-expander.png",
    page: "/docs/energy/losses",
    title: "Performance-ratio losses",
    alt: "The Performance-ratio losses expander open at its defaults, from the inverter efficiency down to other losses, with the shading row greyed out under its auto-compute tick.",
    what: "The expander only, open, at its defaults.",
    state: "Yield tab, open Performance-ratio losses.",
    annotations: "",
    priority: 1,
  },
  {
    id: "yield-group-central",
    file: "energy/yield-group-central.png",
    page: "/docs/energy/losses",
    title: "The loss labels in a central-inverter design",
    alt: "The Energy Yield card in a central-inverter design.",
    what: "The card in that design.",
    state: "Yield tab in a central-inverter design.",
    annotations: "",
    priority: 3,
  },
  {
    id: "degradation-expander",
    file: "energy/degradation-expander.png",
    page: "/docs/energy/lifetime-and-p-values",
    title: "Degradation & lifetime",
    alt: "The Degradation & lifetime expander open: first-year degradation, annual degradation and plant lifetime.",
    what: "The expander only, open, at its defaults.",
    state: "Yield tab, open Degradation & lifetime.",
    annotations: "",
    priority: 1,
  },
  {
    id: "uncertainty-expander",
    file: "energy/uncertainty-expander.png",
    page: "/docs/energy/lifetime-and-p-values",
    title: "Uncertainty & exceedance",
    alt: "The Uncertainty & exceedance expander open: the combined uncertainty and the three exceedance probabilities.",
    what: "The expander only, open, at its defaults.",
    state: "Yield tab, open Uncertainty & exceedance.",
    annotations: "",
    priority: 1,
  },
  {
    id: "energy-view-empty",
    file: "views/energy-empty.png",
    page: "/docs/energy/overview",
    title: "The Energy view before a run",
    alt: "The Energy view before a run: No energy result yet, the note about the weather source, and the Calculate energy button.",
    what: "The whole window on the Energy view after a layout, before Calculate energy.",
    state: "Generate, then click Energy.",
    annotations: "",
    priority: 1,
  },
  {
    id: "energy-view",
    file: "views/energy.png",
    page: "/docs/energy/overview",
    title: "The Energy view after a run",
    alt: "The Energy view after a run: four tiles for year-one energy, specific yield, performance ratio and CUF, the monthly IEC 61724-1 table, the irradiation and performance ratio chart, and the monthly energy bars.",
    what: "The whole window on the Energy view with a result.",
    state: "Click Calculate energy and wait for the fetch.",
    annotations: "",
    priority: 1,
  },
  {
    id: "chart-daily",
    file: "energy/chart-daily.png",
    page: "/docs/energy/timeseries",
    title: "The daily energy chart",
    alt: "The hourly energy window in its daily view: energy bars over irradiance bars for one day, the date controls and the month strip.",
    what: "The chart window on Daily (hourly).",
    state: "After an energy run, click Show Energy Chart.",
    annotations: "",
    priority: 1,
  },
  {
    id: "chart-monthly",
    file: "energy/chart-monthly.png",
    page: "/docs/energy/timeseries",
    title: "The monthly energy chart",
    alt: "The hourly energy window in its monthly view: twelve energy bars and twelve irradiance bars.",
    what: "The chart window on Monthly (yearly).",
    state: "Choose Monthly (yearly) in the view selector.",
    annotations: "",
    priority: 1,
  },
  {
    id: "shadow-view",
    file: "energy/shadow-view.png",
    page: "/docs/energy/shading",
    title: "The Shadow View",
    alt: "The Shadow View window on its Between rows tab: the tilt, pitch and lower-edge inputs, the verdict, the cross-section of three rows with the sun's rays, and the day and solar-time sliders.",
    what: "The window on its first tab.",
    state: "Generate, then click Shadow View (row spacing) on the Tools tab.",
    annotations: "",
    priority: 1,
  },
  {
    id: "layout-fixed-tilt",
    file: "layout/fixed-tilt.png",
    page: "/docs/first-layout",
    title: "A finished fixed-tilt layout",
    alt: "The main window after a fixed-tilt run on the sample site: the placed tables, control rooms and inverters on the plot, and the plant chips filled in.",
    what: "The whole window after Generate Layout.",
    state: "Load the sample site and click Generate Layout.",
    annotations: "",
    priority: 1,
  },
  {
    id: "view-header",
    file: "layout/view-header.png",
    page: "/docs/workspace/views",
    title: "The view tabs and tools",
    alt: "The view header: the Layout, Summary, Energy, BOM and SLD tabs on the left; Save project, Export, Satellite, Wireframe, Piles: OFF, Layers, Sketch, the Home, Pan and Zoom icons and the expand button on the right.",
    what: "The header row only, after a layout.",
    state: "Any window after a layout.",
    annotations: "",
    priority: 1,
  },
  {
    id: "view-header-folded",
    file: "layout/view-header-folded.png",
    page: "/docs/workspace/views",
    title: "The tools on a narrow window",
    alt: "The view header on a narrow window: Satellite, Wireframe and Piles have moved into the Layers popover and the button reads Layers ▾ +3.",
    what: "The header row when the window is too narrow for every tool.",
    state: "Narrow the window until the button reads Layers ▾ +3.",
    annotations: "",
    priority: 2,
  },
  {
    id: "layers-popover",
    file: "layout/layers-popover.png",
    page: "/docs/workspace/views",
    title: "The Layers popover",
    alt: "The Layers popover with its nine rows and their ON/OFF pills: Plant layout ON, Legend OFF, Lightning arresters OFF, ICR blocks OFF, the three cable rows OFF, Contour / terrain OFF, Plant totals ON.",
    what: "The popover at its defaults after a layout.",
    state: "Click Layers ▾.",
    annotations: "",
    priority: 1,
  },
  {
    id: "layers-popover-folded",
    file: "layout/layers-popover-folded.png",
    page: "/docs/workspace/views",
    title: "The Layers popover with the folded tools",
    alt: "The Layers popover on a narrow window, with Satellite image, Wireframe tables and Piles rows at the top.",
    what: "The popover when the view toggles have folded into it.",
    state: "Narrow the window, then click Layers ▾ +3.",
    annotations: "",
    priority: 3,
  },
  {
    id: "layers-popover-central",
    file: "layout/layers-popover-central.png",
    page: "/docs/layout/cables",
    title: "The Layers popover in a central-inverter design",
    alt: "The Layers popover in a central-inverter design, where the second cable row reads DC cables (SMB→CI).",
    what: "The popover in that design.",
    state: "Click Layers ▾ in a central-inverter window.",
    annotations: "",
    priority: 3,
  },
  {
    id: "legend-open",
    file: "layout/legend-open.png",
    page: "/docs/workspace/views",
    title: "The legend opened from its chip",
    alt: "The Layout view with the legend unfolded from the Legend chip in the plot corner.",
    what: "The whole window with the legend open.",
    state: "Click Legend ▾ in the plot corner.",
    annotations: "",
    priority: 2,
  },
  {
    id: "kpi-strip",
    file: "layout/kpi-strip.png",
    page: "/docs/workspace/views",
    title: "The plant chips",
    alt: "The row of plant chips under the view, led by a Design warnings chip: DC capacity, site area, tables, modules, ICR blocks, lightning arresters and year-one P50 energy.",
    what: "The chip row only, after a layout and before an energy run.",
    state: "Any view after a layout.",
    annotations: "",
    priority: 1,
  },
  {
    id: "kpi-strip-energy",
    file: "layout/kpi-strip-energy.png",
    page: "/docs/workspace/views",
    title: "The plant chips after an energy run",
    alt: "The chip row with the lightning arresters and year-one P50 energy chips filled in.",
    what: "The chip row after arresters and energy exist.",
    state: "Generate with arresters on, then calculate energy.",
    annotations: "",
    priority: 2,
  },
  {
    id: "kpi-strip-multi",
    file: "layout/kpi-strip-multi.png",
    page: "/docs/layout/multi-plot",
    title: "The plant chips for three plots",
    alt: "The chip row for a three-plot site, including the Plants chip.",
    what: "The chip row with the Plants chip.",
    state: "Generate a multi-plot file.",
    annotations: "",
    priority: 3,
  },
  {
    id: "expanded-view",
    file: "layout/expanded-view.png",
    page: "/docs/workspace/views",
    title: "The Expanded View window",
    alt: "The plot opened in the Expanded View window with a full toolbar and the Return to Main Window button.",
    what: "The expanded window.",
    state: "Click the expand button at the right of the view tools.",
    annotations: "",
    priority: 2,
  },
  {
    id: "satellite",
    file: "layout/satellite.png",
    page: "/docs/layout/how-placement-works",
    title: "The layout over aerial imagery",
    alt: "The Layout view with the aerial photograph of the site behind the placed tables.",
    what: "The whole window with Satellite on.",
    state: "Generate, then click Satellite. Needs an internet connection.",
    annotations: "",
    priority: 1,
  },
  {
    id: "wireframe",
    file: "layout/wireframe.png",
    page: "/docs/layout/how-placement-works",
    title: "Tables as outlines",
    alt: "A zoomed view of the plot with the tables drawn as outlines only.",
    what: "A zoomed plot with Wireframe on.",
    state: "Click Wireframe, then zoom with the wheel.",
    annotations: "",
    priority: 2,
  },
  {
    id: "arresters",
    file: "layout/arresters.png",
    page: "/docs/layout/lightning-arresters",
    title: "Lightning arresters and their coverage",
    alt: "The Layout view with the arresters and their circular protection areas drawn over the whole plant.",
    what: "The whole window with the Lightning arresters layer on.",
    state: "Generate with Place Lightning Arresters ticked, then switch the layer on.",
    annotations: "",
    priority: 1,
  },
  {
    id: "arresters-detail",
    file: "layout/arresters-detail.png",
    page: "/docs/layout/lightning-arresters",
    title: "Arresters close up",
    alt: "A zoomed view of the plot showing the arrester rectangles, their labels and the overlapping protection circles among the tables.",
    what: "A zoomed plot with the layer on.",
    state: "Zoom into the middle of the plant.",
    annotations: "",
    priority: 1,
  },
  {
    id: "arresters-tracker",
    file: "layout/arresters-tracker.png",
    page: "/docs/layout/lightning-arresters",
    title: "Arresters on a tracker plant",
    alt: "A zoomed tracker layout with the small arrester markers between tracker columns and their protection circles.",
    what: "A zoomed tracker plot with the layer on.",
    state: "In a tracker design, generate with arresters, then zoom.",
    annotations: "",
    priority: 2,
  },
  {
    id: "icr-blocks",
    file: "layout/icr-blocks.png",
    page: "/docs/layout/icr",
    title: "ICR blocks coloured",
    alt: "The Layout view with the ICR blocks layer on: each block — the tables wired to one ICR — filled in its own colour with its outline drawn.",
    what: "The whole window with the layer on.",
    state: "Switch ICR blocks on in Layers.",
    annotations: "",
    priority: 1,
  },
  {
    id: "icr-detail",
    file: "layout/icr-detail.png",
    page: "/docs/layout/icr",
    title: "A control room among the tables",
    alt: "A zoomed view of one inverter control room with its label and the cleared ground around it.",
    what: "A zoomed plot on one control room.",
    state: "Zoom into a control room.",
    annotations: "",
    priority: 1,
  },
  {
    id: "cables-dc-ac",
    file: "layout/cables-dc-ac.png",
    page: "/docs/layout/cables",
    title: "DC and AC cables over the plant",
    alt: "The Layout view with the DC string cables and AC cables layers on across the whole plant.",
    what: "The whole window with both cable layers on.",
    state: "Generate with Calculate cables on, then switch both layers on.",
    annotations: "",
    priority: 1,
  },
  {
    id: "cables-dc-ac-detail",
    file: "layout/cables-dc-ac-detail.png",
    page: "/docs/layout/cables",
    title: "Cable routing close up",
    alt: "A zoomed view around one control room showing the green DC string cables into the inverters and the red AC cables running at right angles to the control room.",
    what: "A zoomed plot around a control room with both cable layers on.",
    state: "Zoom into a control room.",
    annotations: "",
    priority: 1,
  },
  {
    id: "cables-central-detail",
    file: "layout/cables-central-detail.png",
    page: "/docs/layout/cables",
    title: "Cables in a central-inverter design",
    alt: "A zoomed tracker plot in a central-inverter design showing the string cables to the monitoring boxes and the DC trunks to the control room.",
    what: "A zoomed plot in that design with both cable layers on.",
    state: "In a central-inverter design, generate with cables, then zoom.",
    annotations: "",
    priority: 2,
  },
  {
    id: "mcr-mv-cables",
    file: "layout/mcr-mv-cables.png",
    page: "/docs/layout/cables",
    title: "Medium-voltage cables to the main control room",
    alt: "The Layout view after the main control room is placed and the layout regenerated, with the MV cables layer on.",
    what: "The whole window with MV cables drawn.",
    state: "Place MCR, generate again with cables on, then switch MV cables on.",
    annotations: "",
    priority: 1,
  },
  {
    id: "obstructions",
    file: "layout/obstructions.png",
    page: "/docs/layout/obstructions",
    title: "Obstructions clearing tables",
    alt: "The Layout view with the pond, the transmission line corridor, the file's obstruction and a hand-drawn rectangular obstruction, each with the tables cleared.",
    what: "The whole window after drawing one rectangular obstruction.",
    state: "On the Tools tab click Draw Rectangle and drag on the plot.",
    annotations: "",
    priority: 1,
  },
  {
    id: "obstruction-controls",
    file: "layout/obstruction-controls.png",
    page: "/docs/layout/obstructions",
    title: "The Obstructions card",
    alt: "The Obstructions card with Draw Rectangle, Draw Polygon, Undo Last and Clear All.",
    what: "The card only, after a layout.",
    state: "Tools tab after a layout.",
    annotations: "",
    priority: 1,
  },
  {
    id: "obstruction-controls-armed",
    file: "layout/obstruction-controls-armed.png",
    page: "/docs/layout/obstructions",
    title: "The rectangle tool armed",
    alt: "The Obstructions card with Draw Rectangle pressed and the hint Click and drag on the plot to draw a rectangular obstruction.",
    what: "The card with the tool armed so the hint shows.",
    state: "Click Draw Rectangle.",
    annotations: "",
    priority: 2,
  },
  {
    id: "mcr-controls",
    file: "layout/mcr-controls.png",
    page: "/docs/layout/site-equipment",
    title: "Main Control Room & Objects",
    alt: "The Main Control Room & Objects card with Place MCR, Remove MCR, Place Object and Remove Objects.",
    what: "The card only, after a layout.",
    state: "Tools tab after a layout.",
    annotations: "",
    priority: 1,
  },
  {
    id: "mcr-placed-regenerate-hint",
    file: "layout/mcr-placed-regenerate-hint.png",
    page: "/docs/layout/site-equipment",
    title: "After placing the main control room",
    alt: "The Main Control Room & Objects card with the hint MCR placed. Enable 'Cable Calc' and regenerate layout to route MV cables.",
    what: "The card right after the MCR is dropped.",
    state: "Click Place MCR, then click inside the boundary.",
    annotations: "",
    priority: 1,
  },
  {
    id: "mcr-placed-hint",
    file: "layout/mcr-placed-hint.png",
    page: "/docs/layout/site-equipment",
    title: "After regenerating with the MCR",
    alt: "The Main Control Room & Objects card after regenerating, with Remove MCR enabled.",
    what: "The card after the next Generate.",
    state: "Generate again with cables on.",
    annotations: "",
    priority: 3,
  },
  {
    id: "tracker",
    file: "layout/tracker.png",
    page: "/docs/design-modes",
    title: "A finished tracker layout",
    alt: "The main window after a run in a tracker design: the long tracker units running north to south, with the chips reading Trackers.",
    what: "The whole window after Generate Layout in a tracker design.",
    state: "In a tracker design, load the sample site and generate.",
    annotations: "",
    priority: 1,
  },
  {
    id: "terrain",
    file: "layout/terrain.png",
    page: "/docs/inputs/topography",
    title: "Terrain contours",
    alt: "The Layout view with the Contour / terrain layer on: elevation contours drawn across the plant and the Topography box reporting the RL range.",
    what: "The whole window with the terrain layer on.",
    state: "Tick Avoid steep ground, generate, then switch Contour / terrain on.",
    annotations: "",
    priority: 1,
  },
  {
    id: "layers-popover-terrain",
    file: "layout/layers-popover-terrain.png",
    page: "/docs/inputs/topography",
    title: "The terrain row with its RL readout",
    alt: "The Layers popover with Contour / terrain on and its RL readout filled in.",
    what: "The popover after a terrain run.",
    state: "Click Layers ▾ after a terrain run.",
    annotations: "",
    priority: 3,
  },
  {
    id: "multi-plot",
    file: "layout/multi-plot.png",
    page: "/docs/layout/multi-plot",
    title: "A three-plot site",
    alt: "The Layout view with three separate boundaries, each laid out in its own colour and labelled, and the Plants chip reading 3.",
    what: "The whole window after generating a three-boundary file.",
    state: "Generate a multi-boundary file.",
    annotations: "",
    priority: 1,
  },
  {
    id: "uss-multiplot",
    file: "layout/uss-multiplot.png",
    page: "/docs/layout/multi-plot",
    title: "Unit substations across plots",
    alt: "The three-plot layout after Place MCR, with a building dropped in every plot.",
    what: "The whole window after placing the MCR in a multi-plot file.",
    state: "Click Place MCR, then click inside each plot.",
    annotations: "",
    priority: 2,
  },
  {
    id: "summary-view",
    file: "views/summary.png",
    page: "/docs/workspace/views",
    title: "The Summary view",
    alt: "The Summary view: a Metric column and one column for the plant, grouped under SITE, ARRAY, ELECTRICAL and CABLES, with the ACCBs, Transformers (IDT) and Power transformer (MVA) rows.",
    what: "The whole window on the Summary view after a layout.",
    state: "Click Summary.",
    annotations: "",
    priority: 1,
  },
  {
    id: "summary-with-energy",
    file: "views/summary-with-energy.png",
    page: "/docs/reference/summary-columns",
    title: "The Summary view with energy",
    alt: "The Summary view after cables and energy have been calculated, with the cable rows and the ENERGY rows filled in.",
    what: "The whole window on the Summary view with every group populated.",
    state: "Generate with cables, calculate energy, then click Summary.",
    annotations: "",
    priority: 1,
  },
  {
    id: "summary-window",
    file: "views/summary-window.png",
    page: "/docs/reference/summary-columns",
    title: "The summary in its own window",
    alt: "The SolarLayout — Summary window with its Summary and Monthly energy (Year 1) tabs.",
    what: "The separate window on its Summary tab.",
    state: "Click Open in window.",
    annotations: "",
    priority: 2,
  },
  {
    id: "summary-window-monthly",
    file: "views/summary-window-monthly.png",
    page: "/docs/energy/overview",
    title: "The monthly table in its own window",
    alt: "The SolarLayout — Summary window on its Monthly energy (Year 1) tab.",
    what: "The separate window on its monthly tab.",
    state: "After an energy run, click Open in window.",
    annotations: "",
    priority: 3,
  },
  {
    id: "summary-multi-plot",
    file: "views/summary-multi-plot.png",
    page: "/docs/layout/multi-plot",
    title: "The Summary view for three plots",
    alt: "The Summary view with one column per plot and a Total column.",
    what: "The whole window on Summary for a multi-plot file.",
    state: "Generate a multi-plot file, then click Summary.",
    annotations: "",
    priority: 1,
  },
  {
    id: "summary-tracker-central",
    file: "views/summary-tracker-central.png",
    page: "/docs/reference/summary-columns",
    title: "The Summary view in a tracker, central-inverter design",
    alt: "The Summary view in a tracker, central-inverter design, with the tracker and SMB rows.",
    what: "The whole window on Summary in that design.",
    state: "In that design, generate and click Summary.",
    annotations: "",
    priority: 3,
  },
  {
    id: "bom-view",
    file: "views/bom.png",
    page: "/docs/bom/overview",
    title: "The BOM view",
    alt: "The BOM view: the green banner and BOM TOOLS on the left, and the editable bill of materials with its five columns on the right.",
    what: "The whole window on the BOM view.",
    state: "Click BOM.",
    annotations: "",
    priority: 1,
  },
  {
    id: "bom-tools",
    file: "bom/tools.png",
    page: "/docs/bom/overview",
    title: "BOM TOOLS",
    alt: "The BOM TOOLS panel: Add Row, Delete Selected Row, Rebuild from Layout, the BOM Template selector, Load Template, the two exports and the hint.",
    what: "The panel only.",
    state: "Click BOM.",
    annotations: "",
    priority: 2,
  },
  {
    id: "bom-template-window",
    file: "bom/template-window.png",
    page: "/docs/bom/templates",
    title: "A template in its own window",
    alt: "The BOM template window for the matching built-in template, with its rows and the Replace plant BOM with this template button.",
    what: "The template window.",
    state: "Pick the template and click Load Template.",
    annotations: "",
    priority: 1,
  },
  {
    id: "bom-page",
    file: "exports/bom-page1.png",
    page: "/docs/bom/overview",
    title: "The bill of materials exported to PDF",
    alt: "The first page of the bill of materials exported to PDF.",
    what: "Page one of the standalone BOM PDF.",
    state: "Click Export BOM to PDF.",
    annotations: "",
    priority: 2,
  },
  {
    id: "sld-blank",
    file: "views/sld-blank.png",
    page: "/docs/sld/overview",
    title: "The SLD view before generating",
    alt: "The SLD view on entry: the blue banner and SLD TOOLS on the left with neither Automatic nor Manual chosen, and the empty A3 sheet frame on the right.",
    what: "The whole window on the SLD view before a choice.",
    state: "Click SLD.",
    annotations: "",
    priority: 1,
  },
  {
    id: "sld-auto",
    file: "views/sld-auto.png",
    page: "/docs/sld/auto-build",
    title: "An automatically built diagram",
    alt: "The SLD view after Generate: Automatic, with the annotated chain PV array, string inverters, ACCBs, inverter duty transformers, switchgear and grid on the sheet.",
    what: "The whole window after choosing Automatic.",
    state: "Click SLD, then Automatic.",
    annotations: "",
    priority: 1,
  },
  {
    id: "sld-auto-full",
    file: "views/sld-auto-full.png",
    page: "/docs/sld/auto-build",
    title: "The full per-feeder diagram",
    alt: "The SLD view with Full SLD (per-ICR / per-feeder) ticked, showing one feeder row per ACCB grouped by transformer.",
    what: "The whole window with the Full SLD option on.",
    state: "Tick Full SLD (per-ICR / per-feeder).",
    annotations: "",
    priority: 2,
  },
  {
    id: "sld-tools",
    file: "sld/tools.png",
    page: "/docs/sld/symbols",
    title: "SLD TOOLS",
    alt: "The SLD TOOLS panel: the Generate radios, the symbol grid, the image-symbol buttons, rotate, group, view, the Full SLD tick, the import and export buttons.",
    what: "The panel only.",
    state: "Click SLD.",
    annotations: "",
    priority: 1,
  },
  {
    id: "sld-symbol-editor",
    file: "sld/symbol-editor.png",
    page: "/docs/sld/import-and-custom-symbols",
    title: "The Symbol Editor",
    alt: "The Symbol Editor with a traced symbol and the Pen, Erase and Clear tools above Accept and Reject.",
    what: "The editor window with a traced symbol.",
    state: "Click Import Image Symbol and pick an image.",
    annotations: "",
    priority: 2,
  },
  {
    id: "sld-page",
    file: "exports/sld-page1.png",
    page: "/docs/sld/export",
    title: "The diagram exported to PDF",
    alt: "The single-line diagram exported to its own PDF, on the A3 sheet with its title block.",
    what: "The one-page SLD PDF.",
    state: "Click Export SLD to PDF.",
    annotations: "",
    priority: 2,
  },
  {
    id: "sketch-mode",
    file: "editing/sketch-mode.png",
    page: "/docs/editing/sketch-mode",
    title: "Sketch Mode",
    alt: "The main window in Sketch Mode: the orange banner with the Exit button, the grouped tool palette on the left, and the contextual bar above the plot.",
    what: "The whole window with Sketch on.",
    state: "Generate, then click Sketch.",
    annotations: "",
    priority: 1,
  },
  {
    id: "sketch-palette",
    file: "editing/sketch-palette.png",
    page: "/docs/editing/sketch-mode",
    title: "The sketch tool palette",
    alt: "The full sketch palette: PLANT OBJECTS, CABLE TRENCHES, DRAW, ANNOTATE, SELECT & EDIT, MODIFY SELECTION, IMPORT & CLEAR and the COMMAND line.",
    what: "The palette only, unscrolled.",
    state: "Click Sketch.",
    annotations: "",
    priority: 1,
  },
  {
    id: "sketch-palette-more-shapes",
    file: "editing/sketch-palette-more-shapes.png",
    page: "/docs/editing/annotations",
    title: "More shapes",
    alt: "The sketch palette with the More shapes expander open, showing Arc, Ellipse, Spline and Fill/Zone.",
    what: "The palette with More shapes open.",
    state: "Click More shapes.",
    annotations: "",
    priority: 2,
  },
  {
    id: "sketch-palette-selection",
    file: "editing/sketch-palette-selection.png",
    page: "/docs/editing/annotations",
    title: "Modify selection enabled",
    alt: "The sketch palette with several tables selected, so Rotate, Scale, Mirror, Offset and Array are enabled.",
    what: "The palette while a selection exists.",
    state: "Select some tables with Move.",
    annotations: "",
    priority: 2,
  },
  {
    id: "sketch-palette-tracker",
    file: "editing/sketch-palette-tracker.png",
    page: "/docs/editing/sketch-mode",
    title: "The palette on a tracker plant",
    alt: "The sketch palette in a tracker design, where the plant objects read Tracker and Half Tracker.",
    what: "The palette in that design.",
    state: "Click Sketch in a tracker window.",
    annotations: "",
    priority: 3,
  },
  {
    id: "sketch-context-bar",
    file: "editing/sketch-context-bar.png",
    page: "/docs/editing/sketch-mode",
    title: "The contextual bar",
    alt: "The orange contextual bar: Snap, Ortho, Grid with its spacing, Colour, the Layer combo with its add and visibility buttons, the numeric entry, the coordinate readout, Undo and Redo.",
    what: "The bar only.",
    state: "Click Sketch.",
    annotations: "",
    priority: 1,
  },
  {
    id: "sketch-selection",
    file: "editing/sketch-selection.png",
    page: "/docs/editing/sketch-mode",
    title: "Selected tables",
    alt: "A zoomed plot with a block of tables highlighted in gold as the current selection.",
    what: "A zoomed plot with a selection.",
    state: "With Move, drag on empty space across a group of tables.",
    annotations: "",
    priority: 1,
  },
  {
    id: "scale-bar-north",
    file: "editing/scale-bar-north.png",
    page: "/docs/editing/annotations",
    title: "Scale bar and north arrow",
    alt: "The plot with the scale bar and north arrow shown by the Scale bar + N tool.",
    what: "A plot with the decoration on.",
    state: "Click Scale bar + N.",
    annotations: "",
    priority: 2,
  },
  {
    id: "pile-editor",
    file: "editing/pile-editor.png",
    page: "/docs/editing/piles",
    title: "The Pile layout window",
    alt: "The Pile layout window for a plant without half tables: an auto grid of eight piles on one table, the coordinate list on the left, the plant total in the footer and the Apply to all tables button.",
    what: "The window with a pattern placed.",
    state: "Click Piles: OFF, then Auto grid… and place the piles.",
    annotations: "",
    priority: 1,
  },
  {
    id: "piles-overlay",
    file: "editing/piles-overlay.png",
    page: "/docs/editing/piles",
    title: "Piles on the tables",
    alt: "A zoomed view of one table with its piles drawn and labelled.",
    what: "A zoomed plot with the overlay on.",
    state: "Apply a pattern, then zoom into a table.",
    annotations: "",
    priority: 1,
  },
  {
    id: "piles-layout-off",
    file: "editing/piles-layout-off.png",
    page: "/docs/editing/piles",
    title: "Piles with the plant layout off",
    alt: "The same zoomed view with Plant layout switched off so only the piles and their coordinates remain.",
    what: "A zoomed plot with Plant layout off and the overlay on.",
    state: "Switch Plant layout off in Layers.",
    annotations: "",
    priority: 2,
  },
  {
    id: "view-header-piles-on",
    file: "layout/view-header-piles-on.png",
    page: "/docs/editing/piles",
    title: "Piles: ON",
    alt: "The view header with the Piles button reading Piles: ON.",
    what: "The header with the overlay on.",
    state: "Apply a pile pattern.",
    annotations: "",
    priority: 3,
  },
  {
    id: "studies",
    file: "simulation/studies.png",
    page: "/docs/simulation/ac-capacity",
    title: "The Studies card",
    alt: "The Studies card with five buttons: Simulation with AC Capacity, Robotic Module Cleaning, Robot count from DXF…, Shadow View (row spacing) and Earthing Design.",
    what: "The card only, after a layout.",
    state: "Tools tab after a layout.",
    annotations: "",
    priority: 1,
  },
  {
    id: "ac-capacity",
    file: "simulation/ac-capacity.png",
    page: "/docs/simulation/ac-capacity",
    title: "Simulation with AC Capacity",
    alt: "The Simulation with AC Capacity window: the TARGET and EQUIPMENT cards on the left; on the right the verdict Fits this layout, the capacity meter, the result tiles and the ICR block AC row, and the Regenerate layout button.",
    what: "The window with a module and an inverter file loaded and a target that fits.",
    state: "Load a .PAN and a .OND, generate, then click Simulation with AC Capacity.",
    annotations: "",
    priority: 1,
  },
  {
    id: "robotic-cleaning",
    file: "simulation/robotic-cleaning.png",
    page: "/docs/simulation/robotic-cleaning",
    title: "Robotic module cleaning",
    alt: "The Robotic module cleaning window: the ROBOT inputs and the RESULT tiles on the left, the list of gaps too wide for a standard bridge on the right, and the Add to BOM button.",
    what: "The window as it opens for the sample plant.",
    state: "Generate, then click Robotic Module Cleaning.",
    annotations: "",
    priority: 1,
  },
  {
    id: "export-menu",
    file: "exports/export-menu.png",
    page: "/docs/exports/project-report",
    title: "The Export menu",
    alt: "The Export menu: Export KMZ, Export DXF, Export ICR-Block DXF, Export ICR-Block PDF, Export Cable Schedule (Excel), Export Detailed Project Report and Export Image (PNG).",
    what: "The menu as it opens after a layout.",
    state: "Click Export ▾.",
    annotations: "",
    priority: 1,
  },
  {
    id: "export-menu-piles",
    file: "exports/export-menu-piles.png",
    page: "/docs/editing/piles",
    title: "The Export menu with piles on",
    alt: "The Export menu with the extra Export PDF (with Piles) item, shown while the pile overlay is on.",
    what: "The menu while Piles is on.",
    state: "Apply a pile pattern, then click Export ▾.",
    annotations: "",
    priority: 2,
  },
  {
    id: "report-page-drawing",
    file: "exports/report-with-piles-page1.png",
    page: "/docs/exports/project-report",
    title: "The site layout plan page",
    alt: "The site layout plan as the report draws it: the plant in a bordered sheet with a north arrow, the plant-details table and the title block.",
    what: "Page one of the PDF with piles, at page-fit zoom.",
    state: "Export PDF (with Piles) and open page one.",
    annotations: "",
    priority: 1,
  },
  {
    id: "report-page-summary",
    file: "exports/report-with-piles-page2.png",
    page: "/docs/exports/project-report",
    title: "The design summary page",
    alt: "The design summary page of the report with the layout summary, design parameters and cable tables.",
    what: "Page two of the PDF with piles.",
    state: "Open page two.",
    annotations: "",
    priority: 2,
  },
  {
    id: "report-page-sld",
    file: "exports/report-with-piles-page3.png",
    page: "/docs/sld/export",
    title: "The diagram page of the report",
    alt: "The single-line diagram page of the report on its drawing sheet.",
    what: "Page three of the PDF with piles.",
    state: "Open page three.",
    annotations: "",
    priority: 2,
  },
  {
    id: "report-page-bom",
    file: "exports/report-with-piles-page4.png",
    page: "/docs/exports/project-report",
    title: "The bill of materials page",
    alt: "A bill of materials page from the report.",
    what: "Page four of the PDF with piles.",
    state: "Open page four.",
    annotations: "",
    priority: 3,
  },
  {
    id: "dxf-rendered",
    file: "exports/dxf-rendered.png",
    page: "/docs/exports/dxf",
    title: "The exported drawing",
    alt: "The exported DXF drawn from its layers: the boundary, perimeter road, water, tables, control rooms, inverters, cables and trenches.",
    what: "The exported drawing rendered from the file.",
    state: "Export DXF and open it in a CAD viewer.",
    annotations: "",
    priority: 1,
  },
  {
    id: "file-menu",
    file: "projects/file-menu.png",
    page: "/docs/projects",
    title: "The File menu",
    alt: "The File menu: New Project, Move to String / Central Window, Save Project, Open Project, Open Sample Site and Exit with their shortcuts.",
    what: "The menu open.",
    state: "Click File.",
    annotations: "",
    priority: 1,
  },
  {
    id: "edit-pile-menu",
    file: "projects/edit-pile-menu.png",
    page: "/docs/editing/piles",
    title: "The Edit-Pile menu",
    alt: "The Edit-Pile menu with Define Pile Layout.",
    what: "The menu open.",
    state: "Click Edit-Pile.",
    annotations: "",
    priority: 3,
  },
  {
    id: "help-menu",
    file: "support/help-menu.png",
    page: "/docs/support",
    title: "The Help menu",
    alt: "The Help menu with How to Use This Tool and License / Subscription.",
    what: "The menu open.",
    state: "Click Help.",
    annotations: "",
    priority: 2,
  },
  {
    id: "help-dialog",
    file: "support/help-dialog.png",
    page: "/docs/support",
    title: "The in-app guide",
    alt: "The Help — SolarLayout window on its first tab with the tab strip visible.",
    what: "The guide window.",
    state: "Press F1.",
    annotations: "",
    priority: 2,
  },
  {
    id: "support-dialog",
    file: "support/support-dialog.png",
    page: "/docs/support",
    title: "The Support / Feedback window",
    alt: "The Support / Feedback window with the subject, category and description fields and the Send button.",
    what: "The window as it opens.",
    state: "Click Support in the ribbon.",
    annotations: "",
    priority: 1,
  },
  {
    id: "licence-active",
    file: "licence/active.png",
    page: "/docs/licence/activate",
    title: "The License window with active access",
    alt: "The License / Subscription window on a device with active access: the Active headline with the date, and the Access Details, Support cases, Refresh and Close buttons.",
    what: "The window on a device with active access.",
    state: "Open Help ▸ License / Subscription…",
    annotations: "",
    priority: 1,
  },
  {
    id: "licence-no-access",
    file: "licence/no-access.png",
    page: "/docs/licence/activate",
    title: "The License window before activation",
    alt: "The License / Subscription window on a device with no access: the Start your free trial headline, the Get Free Access and Contact Us buttons, and the Having trouble? disclosure.",
    what: "The window on a device that has not been activated.",
    state: "Open Help ▸ License / Subscription… on a new device.",
    annotations: "",
    priority: 1,
  },
  {
    id: "tools-menu",
    file: "simulation/tools-menu.png",
    page: "/docs/workspace/main-window",
    title: "The Tools menu",
    alt: "The Tools menu with Robot count from DXF… and Earthing Design….",
    what: "The menu open.",
    state: "Click Tools in the menu bar.",
    annotations: "",
    priority: 2,
  },
  {
    id: "out-of-date",
    file: "views/out-of-date.png",
    page: "/docs/workspace/out-of-date-results",
    title: "A layout that is out of date",
    alt: "The main window after two inputs changed: Regenerate Layout with 2 inputs changed since the last run, amber dots on the Site and Array tabs, the changed field in amber, the Out of date note over the dimmed plot, and the Out of date chip.",
    what: "The whole window on the Layout view after an input changed.",
    state: "Generate, then change the module wattage and the perimeter road width.",
    annotations: "",
    priority: 1,
  },
  {
    id: "out-of-date-changes",
    file: "views/out-of-date-changes.png",
    page: "/docs/workspace/out-of-date-results",
    title: "The list of changes",
    alt: "The Changed since the last run list naming each changed input with its value at the last run.",
    what: "The popover opened from Show 2 changes.",
    state: "Click Show 2 changes on the Out of date note.",
    annotations: "",
    priority: 2,
  },
  {
    id: "summary-out-of-date",
    file: "views/summary-out-of-date.png",
    page: "/docs/workspace/out-of-date-results",
    title: "The Summary view out of date",
    alt: "The Summary view with its out-of-date banner above the figures from the last run.",
    what: "The whole window on the Summary view while out of date.",
    state: "Change an input after a run, then click Summary.",
    annotations: "",
    priority: 2,
  },
  {
    id: "export-menu-out-of-date",
    file: "exports/export-menu-out-of-date.png",
    page: "/docs/workspace/out-of-date-results",
    title: "The Export menu out of date",
    alt: "The Export menu with the row Inputs changed since the last run. Regenerate first. and every item disabled.",
    what: "The menu while the layout is out of date.",
    state: "Change an input after a run, then click Export ▾.",
    annotations: "",
    priority: 1,
  },
  {
    id: "reopened",
    file: "projects/reopened.png",
    page: "/docs/projects",
    title: "A reopened project",
    alt: "The main window after Open Project: the saved layout on the plot, the view tools enabled and the status Opened Demo.slp · the layout matches its inputs.",
    what: "The whole window straight after opening a saved project.",
    state: "Save a project after Generate, then open it in a new window.",
    annotations: "",
    priority: 2,
  },
  {
    id: "summary-design-warnings",
    file: "views/summary-design-warnings.png",
    page: "/docs/reference/design-warnings",
    title: "Design warnings in the Summary view",
    alt: "The Summary view with the 2 design warnings banner: 78 AC feeders drop more than 2.5 % and the plant's LV AC drop averages 2.25 %, over the 1.5 % budget; the Design warnings chip reads 2.",
    what: "The whole window on the Summary view with two warnings.",
    state: "Tick Calculate cables, set ICR Block to 60 MWp, generate, then click Summary.",
    annotations: "",
    priority: 1,
  },
  {
    id: "kpi-strip-warnings",
    file: "views/kpi-strip-warnings.png",
    page: "/docs/reference/design-warnings",
    title: "The Design warnings chip",
    alt: "The plant chips led by the Design warnings chip reading 2.",
    what: "The chip row with two warnings.",
    state: "As for the Summary with design warnings.",
    annotations: "",
    priority: 2,
  },
  {
    id: "bom-design-warnings",
    file: "views/bom-design-warnings.png",
    page: "/docs/reference/design-warnings",
    title: "Design warnings in the BOM",
    alt: "The BOM view with the AC Cable (Inverter → ICR) row tinted and carrying a Check: remark for the feeder-drop warning.",
    what: "The whole window on the BOM view with two warnings.",
    state: "As for the Summary with design warnings, then click BOM.",
    annotations: "",
    priority: 2,
  },
  {
    id: "report-page-warnings",
    file: "exports/report-warnings-page2.png",
    page: "/docs/reference/design-warnings",
    title: "Design warnings on the PDF summary page",
    alt: "The PDF report's summary page carrying the DESIGN WARNINGS block with each warning's plant, check and finding.",
    what: "Page two of the PDF with piles, exported with two warnings.",
    state: "Export PDF (with Piles) with the warnings present.",
    annotations: "",
    priority: 2,
  },
  {
    id: "dxf-site-utm",
    file: "inputs/dxf-site-utm.png",
    page: "/docs/inputs/cad-boundary",
    title: "A drawing in UTM coordinates",
    alt: "The Site reference window for a drawing whose coordinates look like UTM: the Drawing's coordinates option with a UTM zone chosen and the Use UTM zone 42N button.",
    what: "The window for a UTM-shaped .dxf.",
    state: "Browse to a .dxf drawn in UTM coordinates and pick its zone.",
    annotations: "",
    priority: 1,
  },
  {
    id: "dxf-site-layout-only",
    file: "inputs/dxf-site-layout-only.png",
    page: "/docs/inputs/cad-boundary",
    title: "Layout only",
    alt: "The Site reference window with Layout only chosen: an optional latitude for tilt and row pitch, the banner on what is not available, and the Continue with layout only button.",
    what: "The window with Layout only chosen.",
    state: "Browse to a .dxf and choose Layout only.",
    annotations: "",
    priority: 2,
  },
  {
    id: "accb-transformer-group",
    file: "inputs/accb-transformer-group.png",
    page: "/docs/inputs/accb-and-transformers",
    title: "The ACCB & Transformer card",
    alt: "The ACCB & Transformer card at its defaults: inverters per ACCB, ACCBs per transformer, transformer size limit, the standard transformer ratings, MV voltage, the power transformer margin, derating and ratings, and the LV voltage line.",
    what: "The card before an inverter file and a layout.",
    state: "Electrical tab, nothing loaded.",
    annotations: "",
    priority: 1,
  },
  {
    id: "accb-transformer-group-ond",
    file: "inputs/accb-transformer-group-ond.png",
    page: "/docs/inputs/accb-and-transformers",
    title: "The card after a layout",
    alt: "The ACCB & Transformer card after a layout with an inverter file: LV voltage 800 V from the OND and the answer line Now: 12 ACCBs · 5 transformers: 4 × 10,000 + 1 × 16,000 kVA.",
    what: "The card after loading an OND and generating.",
    state: "Load an OND, generate, then open the Electrical tab.",
    annotations: "",
    priority: 1,
  },
  {
    id: "icr-block-selected",
    file: "layout/icr-block-selected.png",
    page: "/docs/layout/icr-blocks",
    title: "A block selected from the keyboard",
    alt: "The Layout view with the ICR blocks layer on and ICR-1 outlined as the keyboard selection; the status bar reads ICR-1 selected — press Enter to open its summary.",
    what: "The whole window with one block selected.",
    state: "Switch ICR blocks on, click the plot, then press an arrow key.",
    annotations: "",
    priority: 2,
  },
  {
    id: "icr-block-summary",
    file: "layout/icr-block-summary.png",
    page: "/docs/layout/icr-blocks",
    title: "An ICR block summary window",
    alt: "The ICR-1 — Demo window: tiles for DC capacity, tables, modules and string inverters, then block area, perimeter, ACCBs, transformer, transformer load, inverter and AC capacity, DC/AC ratio, cable lengths, arresters and piles, with PDF…, Copy and Close.",
    what: "The window for one block.",
    state: "With ICR blocks on, click a block.",
    annotations: "",
    priority: 1,
  },
  {
    id: "icr-block-out-of-date",
    file: "layout/icr-block-out-of-date.png",
    page: "/docs/layout/icr-blocks",
    title: "A block window out of date",
    alt: "An ICR block summary window with its out-of-date banner and PDF… and Copy disabled.",
    what: "The window opened while the layout is out of date.",
    state: "Change an input after a run, then click a block.",
    annotations: "",
    priority: 3,
  },
  {
    id: "icr-block-pdf-plant",
    file: "exports/icr-blocks-page1.png",
    page: "/docs/layout/icr-blocks",
    title: "The ICR-Block PDF: the plant sheet",
    alt: "Sheet 1 of the ICR-Block PDF: the plant with each block in colour and the ICR BLOCKS table of area, tables, modules, DC, inverters, AC and DC/AC per block.",
    what: "Page one of the ICR-Block PDF.",
    state: "Export ▾ ▸ Export ICR-Block PDF.",
    annotations: "",
    priority: 1,
  },
  {
    id: "icr-block-pdf-block",
    file: "exports/icr-blocks-page2.png",
    page: "/docs/layout/icr-blocks",
    title: "The ICR-Block PDF: a block sheet",
    alt: "A block sheet of the ICR-Block PDF: the block drawn with its key plan and the BLOCK DETAILS table.",
    what: "Page two of the ICR-Block PDF.",
    state: "Export ▾ ▸ Export ICR-Block PDF.",
    annotations: "",
    priority: 2,
  },
  {
    id: "pile-editor-half-full",
    file: "editing/pile-editor-half-full.png",
    page: "/docs/editing/piles",
    title: "The Full tab on a plant with half tables",
    alt: "The Pile layout window on a plant with half tables: the Full table · Half table switch, the note that half tables follow this pattern, eight piles on the full table and the plant total.",
    what: "The window on the Full tab with a pattern placed.",
    state: "Generate with Add half tables on, place a pattern, open Piles.",
    annotations: "",
    priority: 1,
  },
  {
    id: "pile-editor-half-derived",
    file: "editing/pile-editor-half-derived.png",
    page: "/docs/editing/piles",
    title: "The derived half pattern",
    alt: "The Half table tab showing the pattern derived from the full table — same end overhang, even spans — drawn on the half table beside the dashed full outline.",
    what: "The window on the Half tab before any edit.",
    state: "Click Half table.",
    annotations: "",
    priority: 1,
  },
  {
    id: "pile-editor-half-own",
    file: "editing/pile-editor-half-own.png",
    page: "/docs/editing/piles",
    title: "An own half pattern",
    alt: "The Half table tab after an auto grid: the note Your own pattern for half tables and the Reset to derived button.",
    what: "The Half tab after editing the pattern.",
    state: "On the Half tab, place piles with Auto grid….",
    annotations: "",
    priority: 2,
  },
  {
    id: "pile-editor-half-changed",
    file: "editing/pile-editor-half-changed.png",
    page: "/docs/editing/piles",
    title: "A half pattern made for an earlier full pattern",
    alt: "The Full tab with the warning Half tables use your own pattern, made for an earlier full table, and the Review button.",
    what: "The Full tab after the full pattern changed under an own half pattern.",
    state: "Change the full pattern after making an own half pattern.",
    annotations: "",
    priority: 2,
  },
  {
    id: "pile-editor-half-tracker",
    file: "editing/pile-editor-half-tracker.png",
    page: "/docs/editing/piles",
    title: "A half tracker's derived pattern",
    alt: "The Half tracker tab of the Pile layout window: the derived pattern with a drive pile at the centre of the half tracker.",
    what: "The Half tab in a tracker design.",
    state: "Generate a tracker design with Add half trackers on, place a pattern, click Half tracker.",
    annotations: "",
    priority: 2,
  },
  {
    id: "ac-capacity-icr-block",
    file: "simulation/ac-capacity-icr-block.png",
    page: "/docs/simulation/ac-capacity",
    title: "ICR block AC set",
    alt: "The Simulation with AC Capacity window with ICR block AC set to 18600 kW and the hint → 2 blocks of 24.180 MWp DC.",
    what: "The window with ICR block AC filled in.",
    state: "Type an AC capacity per block into ICR block AC.",
    annotations: "",
    priority: 2,
  },
  {
    id: "robot-dxf",
    file: "simulation/robot-dxf.png",
    page: "/docs/simulation/robot-count-from-dxf",
    title: "Robot count from DXF",
    alt: "The Robot count from DXF window with a plant drawing read: the DRAWING and ROBOT cards and the verdict on the left, the four tiles and the Layout view of the drawing with its gaps on the right, and Export PDF….",
    what: "The window after reading a drawing.",
    state: "Tools ▸ Robot count from DXF…, then Open DXF….",
    annotations: "",
    priority: 1,
  },
  {
    id: "robot-dxf-gaps",
    file: "simulation/robot-dxf-gaps.png",
    page: "/docs/simulation/robot-count-from-dxf",
    title: "The Gaps view",
    alt: "The Gaps view: the wide gaps listed by filter with three ticked for bridging, and the verdict counting the bridges.",
    what: "The window on Gaps with some gaps ticked.",
    state: "Click Gaps and tick the gaps you will bridge.",
    annotations: "",
    priority: 1,
  },
  {
    id: "robot-dxf-rows",
    file: "simulation/robot-dxf-rows.png",
    page: "/docs/simulation/robot-count-from-dxf",
    title: "The Rows view",
    alt: "The Rows view: each cleaning line with its tables, segments, longest segment and robots, beside a verdict of 234 robots with 3 bridges.",
    what: "The window on Rows.",
    state: "Click Rows.",
    annotations: "",
    priority: 3,
  },
  {
    id: "robot-dxf-layers",
    file: "simulation/robot-dxf-layers.png",
    page: "/docs/simulation/robot-count-from-dxf",
    title: "The Layers view",
    alt: "The Layers view: every layer of the drawing with the role guessed from its name, editable in a list.",
    what: "The window on Layers.",
    state: "Click Layers.",
    annotations: "",
    priority: 2,
  },
  {
    id: "robot-dxf-pdf",
    file: "exports/robot-count-page1.png",
    page: "/docs/simulation/robot-count-from-dxf",
    title: "The robot count PDF",
    alt: "Page one of the robot count PDF: the answer, the inputs and the plan.",
    what: "Page one of the exported PDF.",
    state: "Click Export PDF….",
    annotations: "",
    priority: 3,
  },
  {
    id: "earthing-layout",
    file: "simulation/earthing-layout.png",
    page: "/docs/simulation/earthing",
    title: "Earthing Design",
    alt: "The Earthing Design window: the verdict 284 earth pits · plant grid 0.11 Ω (target ≤ 1 Ω), the Soil & site and Fault data inputs on the left, and the Layout tab drawing the conductors and earth pits over the plant with its legend.",
    what: "The window on the Layout tab at the defaults.",
    state: "Generate, then Tools ▸ Earthing Design….",
    annotations: "",
    priority: 1,
  },
  {
    id: "earthing-calculation",
    file: "simulation/earthing-calculation.png",
    page: "/docs/simulation/earthing",
    title: "The Calculation tab",
    alt: "The Calculation tab of Earthing Design: the numbered calculation report with the design basis and each step.",
    what: "The window on the Calculation tab.",
    state: "Click Calculation.",
    annotations: "",
    priority: 1,
  },
  {
    id: "earthing-boq",
    file: "simulation/earthing-boq.png",
    page: "/docs/simulation/earthing",
    title: "The BoQ tab",
    alt: "The BoQ tab of Earthing Design: S.No, Description, Qty, Unit and Remark for the strips, cable, pits and accessories.",
    what: "The window on the BoQ tab.",
    state: "Click BoQ.",
    annotations: "",
    priority: 1,
  },
  {
    id: "earthing-warn",
    file: "simulation/earthing-warn.png",
    page: "/docs/simulation/earthing",
    title: "A target the grid does not meet",
    alt: "Earthing Design with a whole-plant target of 0.10 Ω, which the plant grid does not meet: the verdict turns to a warning.",
    what: "The window with a target below the plant grid's resistance.",
    state: "Set Targets ▸ Whole plant below the computed grid value.",
    annotations: "",
    priority: 2,
  },
  {
    id: "earthing-pdf",
    file: "exports/earthing-page1.png",
    page: "/docs/simulation/earthing",
    title: "The earthing report",
    alt: "Page one of the earthing PDF report.",
    what: "Page one of the exported report.",
    state: "Click Export PDF report….",
    annotations: "",
    priority: 3,
  },
]

/** Lookup used by `<Screenshot id="…" />`. */
export const SCREENSHOTS_BY_ID: Record<string, ScreenshotSpec> =
  Object.fromEntries(SCREENSHOTS.map((s) => [s.id, s]))
