/**
 * Screenshot manifest — the single source of truth for every image the docs
 * reference.
 *
 * Two consumers read this file, which is why it exists at all:
 *
 *   1. `<Screenshot id="…" />` (components/ui/screenshot.tsx) renders the
 *      image when the file is present under `public/screenshots/`, and a
 *      placeholder carrying `what` + `state` when it is not.
 *   2. `scripts/build-screenshot-index.mjs` emits `docs/screenshot-index.xlsx`
 *      — the capture worklist handed to whoever takes the screenshots.
 *
 * Because both read the same rows, the worklist can never drift from the
 * pages, and a captured file needs no code change: drop it at
 * `public/screenshots/<file>` and it appears.
 *
 * SolarLayout Desktop has a single visual theme, so there is exactly ONE
 * image per entry — no light/dark pairs.
 *
 * `priority` lets the capture work happen in waves:
 *   1 — essential; the page does not make sense without it
 *   2 — valuable; explains something the prose can only describe
 *   3 — nice to have; polish
 */
export interface ScreenshotSpec {
  /** Stable id used in MDX: `<Screenshot id="…" />`. */
  id: string
  /** Path under `public/screenshots/`. */
  file: string
  /** Docs page that uses it, for the capture worklist. */
  page: string
  /** Short human title — the placeholder heading and the worklist row title. */
  title: string
  /** Alt text. Describes the content, not the act of screenshotting. */
  alt: string
  /** What the frame must contain. */
  what: string
  /** How to get the app into that state before capturing. */
  state: string
  /** Callouts to add after capture. Empty string when none. */
  annotations: string
  priority: 1 | 2 | 3
}

export const SCREENSHOTS: ScreenshotSpec[] = [
  // ── Install and licence ────────────────────────────────────────────────
  {
    id: "store-listing",
    file: "install/store-listing.png",
    page: "/docs/install/windows",
    title: "Microsoft Store listing",
    alt: "The SolarLayout Desktop listing in the Microsoft Store, showing the publisher and the Get button.",
    what: "The Microsoft Store app open on the SolarLayout Desktop listing, with the publisher name and the Get / Install button visible.",
    state: "Open the Microsoft Store and search for SolarLayout Desktop. Capture before installing so the button reads Get or Install.",
    annotations: "Outline the publisher name and the Get button.",
    priority: 1,
  },
  {
    id: "store-installed",
    file: "install/store-installed.png",
    page: "/docs/install/windows",
    title: "Store listing after install",
    alt: "The Store listing after installation, with an Open button in place of Get.",
    what: "The same listing once installation has finished — the button now reads Open.",
    state: "Immediately after the install completes, before launching the app.",
    annotations: "Outline the Open button.",
    priority: 3,
  },
  {
    id: "start-menu-entry",
    file: "install/start-menu-entry.png",
    page: "/docs/install/windows",
    title: "Start menu entry",
    alt: "The Windows Start menu with SolarLayout Desktop in the results.",
    what: "The Windows Start menu with SolarLayout Desktop shown as a result.",
    state: "Press Start and type the first few letters of the app name.",
    annotations: "",
    priority: 2,
  },
  {
    id: "store-updates",
    file: "install/store-updates.png",
    page: "/docs/install/updates",
    title: "Store downloads and updates",
    alt: "The Microsoft Store library page listing available updates.",
    what: "The Store's Library / Downloads and updates page, with the Get updates button visible.",
    state: "Open the Microsoft Store, then the Library from the left-hand navigation.",
    annotations: "Outline the Get updates button.",
    priority: 2,
  },
  {
    id: "licence-no-licence",
    file: "licence/no-licence.png",
    page: "/docs/licence/activate",
    title: "License window before activation",
    alt: "The License and Subscription window showing no licence found, with the Device ID field and a Copy button.",
    what: "Help ▸ License / Subscription… on a machine with no licence installed: the status banner, the Device ID box with its Copy button, and the Load License File… button.",
    state: "Launch the app on a machine that has never had a licence installed, then open Help ▸ License / Subscription…",
    annotations: "Number the Device ID field 1 and the Load License File… button 2. Blur the Device ID value itself.",
    priority: 1,
  },
  {
    id: "licence-valid",
    file: "licence/valid.png",
    page: "/docs/licence/activate",
    title: "License window after activation",
    alt: "The License and Subscription window showing a valid licence with its expiry date.",
    what: "The same window after a valid licence has been loaded — the status banner reports the licence as valid and shows the expiry date.",
    state: "Load a valid license.lic through Load License File…, then reopen the window.",
    annotations: "Outline the status banner. Blur the email address and Device ID.",
    priority: 1,
  },
  {
    id: "licence-blocked-generate",
    file: "licence/blocked-generate.png",
    page: "/docs/licence/overview",
    title: "Generate blocked without a licence",
    alt: "The message shown when Generate Layout is clicked without a valid licence.",
    what: "The message the app shows when Generate Layout is clicked and no valid licence is present.",
    state: "With no licence installed, load a boundary file and click Generate Layout.",
    annotations: "",
    priority: 2,
  },

  // ── First run ──────────────────────────────────────────────────────────
  {
    id: "startup-design-modes",
    file: "start/design-modes.png",
    page: "/docs/design-modes",
    title: "Design mode selection",
    alt: "The startup dialog offering four design modes as cards: Fixed Tilt or Single Axis Tracker, each with String or Central Inverter.",
    what: "The full startup dialog: the title, the two column headers (Fixed Tilt, Single Axis Tracker) and all four cards with their Select buttons.",
    state: "Launch the app. The dialog is the first thing shown, before the main window.",
    annotations: "",
    priority: 1,
  },
  {
    id: "main-window-empty",
    file: "start/main-window-empty.png",
    page: "/docs/getting-started",
    title: "Main window before a layout",
    alt: "The main window with the input panel on the left and an empty plot area on the right.",
    what: "The whole main window straight after choosing a design mode: input panel on the left, empty plot area, toolbar, and the empty summary table.",
    state: "Pick Fixed Tilt + String Inverter at startup and capture before loading any file. Maximise the window first.",
    annotations: "Bracket the left third and label it Input panel; bracket the right and label it Plot area.",
    priority: 1,
  },
  {
    id: "input-panel-full",
    file: "inputs/panel-full.png",
    page: "/docs/inputs/boundary-files",
    title: "The complete input panel",
    alt: "The left-hand input panel with every group visible, from Input KMZ File down to Energy Yield.",
    what: "The input panel scrolled and stitched (or captured on a tall window) so every group heading is visible in one image: Input KMZ File, Module Specifications, MMS-Table Configuration, Spacing & Tilt, Site Parameters, Structures & Shadow, Topography, String Inverter, Energy Yield.",
    state: "Fixed Tilt + String Inverter. No file loaded, so every field is at its default.",
    annotations: "Label each group heading with its number in reading order.",
    priority: 1,
  },
  {
    id: "boundary-file-row",
    file: "inputs/boundary-file-row.png",
    page: "/docs/inputs/boundary-files",
    title: "Input KMZ File row",
    alt: "The Input KMZ File group with the path field, the Browse button and the information button.",
    what: "Just the Input KMZ File group: the read-only path field with its placeholder text, the Browse… button, and the ⓘ button.",
    state: "No file loaded, so the placeholder text is visible.",
    annotations: "Outline the ⓘ button.",
    priority: 1,
  },

  // ── Boundary preparation ───────────────────────────────────────────────
  {
    id: "kmz-help-dialog",
    file: "inputs/kmz-help-dialog.png",
    page: "/docs/inputs/kmz-requirements",
    title: "Boundary preparation guide",
    alt: "The in-app boundary preparation guide listing the rules for boundaries, water bodies, transmission lines and obstructions.",
    what: "The dialog opened by the ⓘ button, scrolled to show the numbered sections and the quick-reference table at the bottom.",
    state: "Click the ⓘ button next to Browse…. Capture twice if needed — the top sections and the quick-reference table.",
    annotations: "",
    priority: 2,
  },
  {
    id: "kmz-in-google-earth",
    file: "inputs/kmz-google-earth.png",
    page: "/docs/inputs/kmz-requirements",
    title: "A correctly prepared boundary file",
    alt: "Google Earth showing a plant boundary polygon containing a named pond polygon, a named building polygon and a transmission line drawn as a line.",
    what: "Google Earth with the Places panel visible, showing one plant boundary polygon that contains a water polygon, an obstruction polygon and a transmission LineString — with the feature names readable in the panel so the naming rules are obvious.",
    state: "Open a prepared demonstration file in Google Earth Pro. Expand the Places tree so every feature name shows.",
    annotations: "Label each feature with its type: boundary, water, obstruction, transmission line.",
    priority: 1,
  },
  {
    id: "boundary-validation-dialog",
    file: "inputs/boundary-validation.png",
    page: "/docs/inputs/kmz-requirements",
    title: "Boundary validation issues",
    alt: "The Boundary Validation Issues dialog listing boundaries with open rings and a checkbox to exclude each one.",
    what: "The dialog listing each problem boundary with its description and exclusion checkbox, plus the buttons at the bottom.",
    state: "Load a file containing at least one boundary whose ring is not closed.",
    annotations: "Outline one row's checkbox.",
    priority: 2,
  },
  {
    id: "dxf-latlon-dialog",
    file: "inputs/dxf-latlon.png",
    page: "/docs/inputs/cad-boundary",
    title: "CAD site coordinates",
    alt: "The DXF Site Coordinates dialog asking for site latitude and longitude.",
    what: "The dialog with its explanation, the latitude and longitude fields, and both buttons including the skip option.",
    state: "Choose a .dxf or .dwg file through Browse…. The dialog opens on its own.",
    annotations: "",
    priority: 1,
  },
  {
    id: "image-scale-dialog",
    file: "inputs/image-scale.png",
    page: "/docs/inputs/image-boundary",
    title: "Image scale and coordinates",
    alt: "The Image Boundary dialog asking how a site distance maps to a drawing distance, plus optional coordinates.",
    what: "The dialog with the scale pair at its defaults and the optional coordinate fields.",
    state: "Choose an image file through Browse…. The dialog opens on its own.",
    annotations: "Outline the two scale fields together and label them the scale pair.",
    priority: 1,
  },

  // ── Module, table, tracker, spacing ────────────────────────────────────
  {
    id: "module-group",
    file: "inputs/module-group.png",
    page: "/docs/inputs/module",
    title: "Module Specifications",
    alt: "The Module Specifications group with the module file row, dimensions, wattage and the bifacial options.",
    what: "The whole Module Specifications group at its defaults, including the Bifacial Options divider and the disabled bifaciality field.",
    state: "No module file loaded, so the row reads that none is loaded and the bifaciality field is greyed out.",
    annotations: "",
    priority: 1,
  },
  {
    id: "module-pan-loaded",
    file: "inputs/module-pan-loaded.png",
    page: "/docs/inputs/module",
    title: "Module group after loading a module file",
    alt: "The Module Specifications group after a module file is loaded, with the module name shown and the dimensions and wattage filled in.",
    what: "The same group after a bifacial module file has been loaded: the module name on the file row, the auto-filled dimensions and wattage, and the Bifacial checkbox now ticked with its factor filled in.",
    state: "Click Load .PAN and pick a bifacial module file. Capture before answering the modules-in-series question, or dismiss it with Manual first.",
    annotations: "Outline the three auto-filled fields and the ticked Bifacial checkbox.",
    priority: 1,
  },
  {
    id: "pan-viewer",
    file: "inputs/pan-viewer.png",
    page: "/docs/inputs/module",
    title: "Module file viewer",
    alt: "The module file viewer showing the parsed parameters across its tabs.",
    what: "The viewer on its first tab, with the tab strip fully visible.",
    state: "Load a module file, then click View next to it.",
    annotations: "",
    priority: 2,
  },
  {
    id: "pan-viewer-graphs",
    file: "inputs/pan-viewer-graphs.png",
    page: "/docs/inputs/module",
    title: "Module current and power curves",
    alt: "The Graphs tab of the module file viewer showing the current-voltage and power-voltage curves.",
    what: "The Graphs tab with both curves drawn and the axes readable.",
    state: "In the module file viewer, open the Graphs tab.",
    annotations: "",
    priority: 3,
  },
  {
    id: "string-sizing-prompt",
    file: "inputs/string-sizing-prompt.png",
    page: "/docs/inputs/string-sizing",
    title: "Automatic or manual string length",
    alt: "The question asking whether to calculate the number of modules in series automatically, with Auto and Manual buttons.",
    what: "The question box with its full explanatory text and both buttons.",
    state: "Load a module file. The question appears on its own straight afterwards.",
    annotations: "",
    priority: 1,
  },
  {
    id: "string-sizing-dialog",
    file: "inputs/string-sizing-dialog.png",
    page: "/docs/inputs/string-sizing",
    title: "Automatic string sizing",
    alt: "The automatic string sizing window showing the feasible range of modules in series and the selection fields.",
    what: "The window with the system voltage and temperature inputs filled, the computed feasible range visible, and the final selection fields.",
    state: "Load a module file and an inverter file, then answer Auto to the modules-in-series question.",
    annotations: "Outline the computed feasible range.",
    priority: 1,
  },
  {
    id: "table-group",
    file: "inputs/table-group.png",
    page: "/docs/inputs/table",
    title: "MMS-Table Configuration",
    alt: "The MMS-Table Configuration group with orientation, module counts, gaps and the two placement options.",
    what: "The whole group at its defaults, including both checkboxes at the bottom.",
    state: "Fixed Tilt mode, nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },
  {
    id: "tracker-group",
    file: "inputs/tracker-group.png",
    page: "/docs/inputs/tracker",
    title: "Tracker Configuration",
    alt: "The Tracker Configuration group with its geometry, row spacing and tracker parameter sections, and the live dimension preview.",
    what: "The whole group at its defaults, including the three section dividers and — importantly — the green live preview line showing aperture, length, ground coverage ratio and modules per tracker.",
    state: "Choose a Single Axis Tracker mode at startup. Nothing changed from defaults.",
    annotations: "Outline the live preview line.",
    priority: 1,
  },
  {
    id: "spacing-tilt-group",
    file: "inputs/spacing-tilt-group.png",
    page: "/docs/inputs/spacing-and-tilt",
    title: "Spacing and tilt",
    alt: "The Spacing and Tilt group with both override checkboxes unticked and the automatic labels shown.",
    what: "The group before any layout has been generated: both override boxes unticked, both value fields greyed out, and both automatic labels showing their placeholder text.",
    state: "Fixed Tilt mode, before clicking Generate Layout.",
    annotations: "",
    priority: 1,
  },
  {
    id: "spacing-tilt-auto-resolved",
    file: "inputs/spacing-tilt-auto-resolved.png",
    page: "/docs/inputs/spacing-and-tilt",
    title: "Automatic tilt and pitch after a layout",
    alt: "The Spacing and Tilt group after a layout, with the automatic labels reporting the derived tilt angle and row pitch.",
    what: "The same group after Generate Layout has run — the two labels now report the derived values in green, and those values are pre-filled into the greyed-out fields.",
    state: "Generate a layout with both overrides left off, then look at the group again.",
    annotations: "Outline both green labels.",
    priority: 1,
  },

  // ── Site, structures, topography ───────────────────────────────────────
  {
    id: "site-group",
    file: "inputs/site-group.png",
    page: "/docs/inputs/site",
    title: "Site Parameters",
    alt: "The Site Parameters group with perimeter road width, the lightning arrester option, protection radius, ICR block and transmission line corridor.",
    what: "The whole group at its defaults, with the arrester option unticked and the protection radius therefore greyed out.",
    state: "Nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },
  {
    id: "structures-group",
    file: "inputs/structures-group.png",
    page: "/docs/inputs/structures-and-shadow",
    title: "Structures and shadow",
    alt: "The Structures and Shadow group with the length, width and height grid for each structure, the shadow window and the street light settings.",
    what: "The whole group at its defaults: the L / W / H column headers, one row each for ICR, MCR, USS and Object, the arrester height and pile diameter row, the shadow window row, the clear-tables checkbox, and the street light section.",
    state: "Nothing changed from defaults.",
    annotations: "Bracket the L / W / H columns and label them Length (east-west), Width (north-south), Height.",
    priority: 1,
  },
  {
    id: "topography-group",
    file: "inputs/topography-group.png",
    page: "/docs/inputs/topography",
    title: "Topography",
    alt: "The Topography group with the enable checkbox, contour data row, slope limits and the depression option.",
    what: "The whole group at its defaults, with terrain disabled and the contour row reading that the satellite elevation model will be used.",
    state: "Nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },

  // ── Inverter and cables input ──────────────────────────────────────────
  {
    id: "inverter-group-string",
    file: "inputs/inverter-group-string.png",
    page: "/docs/inputs/inverter",
    title: "String Inverter group",
    alt: "The String Inverter group with maximum strings per inverter, the cable calculation option and the inverter file row.",
    what: "The whole group in String Inverter mode at its defaults, with the cable option unticked and no inverter file loaded.",
    state: "Choose a String Inverter mode at startup. Nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },
  {
    id: "inverter-group-central",
    file: "inputs/inverter-group-central.png",
    page: "/docs/inputs/inverter",
    title: "SMB group in Central Inverter mode",
    alt: "The SMB group in Central Inverter mode, with maximum strings per SMB and maximum SMBs per central inverter.",
    what: "The same area in Central Inverter mode, showing the different group title and the extra field for SMBs per central inverter.",
    state: "Choose a Central Inverter mode at startup.",
    annotations: "Outline the extra field that only this mode shows.",
    priority: 1,
  },
  {
    id: "cable-calc-warning",
    file: "inputs/cable-calc-warning.png",
    page: "/docs/inputs/inverter",
    title: "Cable calculation notice",
    alt: "The notice warning that cable calculation can be slow, with buttons to enable it now or not yet.",
    what: "The notice with its full text and both buttons, so the recommended choice is visible.",
    state: "Tick the cable calculation option. The notice appears immediately.",
    annotations: "",
    priority: 2,
  },
  {
    id: "ond-loaded",
    file: "inputs/ond-loaded.png",
    page: "/docs/inputs/inverter",
    title: "Inverter file loaded",
    alt: "The inverter file row showing the loaded inverter's make and model.",
    what: "The inverter file row after a file has been loaded, showing the make and model, with the View button now enabled.",
    state: "Click Load .OND and pick an inverter file.",
    annotations: "",
    priority: 2,
  },
  {
    id: "ond-viewer",
    file: "inputs/ond-viewer.png",
    page: "/docs/inputs/inverter",
    title: "Inverter file viewer",
    alt: "The inverter file viewer showing the parsed parameters across its tabs.",
    what: "The viewer on its first tab with the whole tab strip visible.",
    state: "Load an inverter file, then click View next to it.",
    annotations: "",
    priority: 2,
  },
  {
    id: "ond-efficiency-curve",
    file: "inputs/ond-efficiency-curve.png",
    page: "/docs/inputs/inverter",
    title: "Inverter efficiency curve",
    alt: "The efficiency curve tab of the inverter file viewer.",
    what: "The efficiency curve tab with the curve drawn and axes readable.",
    state: "In the inverter file viewer, open the efficiency curve tab.",
    annotations: "",
    priority: 3,
  },

  // ── Energy inputs ──────────────────────────────────────────────────────
  {
    id: "energy-weather-source",
    file: "energy/weather-source.png",
    page: "/docs/energy/weather",
    title: "Weather data source",
    alt: "The weather data source options, with the automatic service selected by default.",
    what: "The top of the Energy Yield group: the weather source divider, both options with the automatic one ticked, and the irradiance fields below with their source label.",
    state: "Nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },
  {
    id: "energy-ghi-file-format",
    file: "energy/ghi-file-format.png",
    page: "/docs/energy/weather",
    title: "Hourly file format reminder",
    alt: "The reminder describing the three columns an hourly weather file must contain.",
    what: "The reminder with its full three-column table.",
    state: "Select the hourly file option. The reminder appears immediately.",
    annotations: "",
    priority: 1,
  },
  {
    id: "energy-ghi-file-loaded",
    file: "energy/ghi-file-loaded.png",
    page: "/docs/energy/weather",
    title: "Hourly file loaded",
    alt: "The weather file row reporting the number of hours read, the annual irradiance and that temperature data was found.",
    what: "The file row after a valid hourly file has been read, showing the summary line, and the source label below the irradiance fields.",
    state: "Select the hourly file option, then Browse… and pick a full-year file that includes a temperature column.",
    annotations: "Outline the summary line.",
    priority: 2,
  },
  {
    id: "energy-irradiance-fetched",
    file: "energy/irradiance-fetched.png",
    page: "/docs/energy/weather",
    title: "Irradiance after an automatic fetch",
    alt: "The irradiance fields filled in automatically, with a source label naming the service used.",
    what: "The irradiance fields after Calculate Energy has fetched them, with the green source label naming the service.",
    state: "With the automatic source selected, generate a layout and click Calculate Energy.",
    annotations: "Outline the source label.",
    priority: 1,
  },
  {
    id: "energy-losses-group",
    file: "energy/losses-group.png",
    page: "/docs/energy/losses",
    title: "Performance ratio breakdown",
    alt: "The performance ratio breakdown listing every loss component with its percentage.",
    what: "The whole performance ratio section at its defaults, including the module temperature readout row, the shading auto-compute checkbox and the ground clearance row.",
    state: "Nothing changed from defaults, in a String Inverter mode so the cable row labels read that way.",
    annotations: "",
    priority: 1,
  },
  {
    id: "energy-temperature-trace",
    file: "energy/temperature-trace.png",
    page: "/docs/energy/temperature",
    title: "Temperature loss calculation",
    alt: "The temperature loss row with the computed module temperature beside it and the formula trace below.",
    what: "The mounting type, wind speed and ambient temperature fields, the temperature loss row with the computed module temperature next to it, and the formula trace line.",
    state: "Load a module file so the temperature model has a coefficient to work with, and set an irradiance value.",
    annotations: "Outline the formula trace line.",
    priority: 1,
  },
  {
    id: "energy-degradation-pvalues",
    file: "energy/degradation-pvalues.png",
    page: "/docs/energy/lifetime-and-p-values",
    title: "Degradation and probability settings",
    alt: "The degradation and probabilistic yield sections with their default values.",
    what: "Both sections together: first-year and annual degradation, plant lifetime, combined uncertainty, and the three exceedance probability fields.",
    state: "Nothing changed from defaults.",
    annotations: "",
    priority: 1,
  },
  {
    id: "energy-bifacial-albedo",
    file: "energy/bifacial-albedo.png",
    page: "/docs/energy/bifacial",
    title: "Ground albedo",
    alt: "The ground albedo field in the energy section.",
    what: "The bifacial ground albedo divider and its field.",
    state: "Nothing changed from defaults.",
    annotations: "",
    priority: 2,
  },

  // ── Generating and reading a layout ───────────────────────────────────
  {
    id: "generate-button",
    file: "layout/generate-button.png",
    page: "/docs/first-layout",
    title: "Generate Layout",
    alt: "The Generate Layout button below the input panel.",
    what: "The Generate Layout button with enough surrounding area to place it in the window.",
    state: "A boundary file loaded and a valid licence installed, so the button is enabled.",
    annotations: "Outline the button.",
    priority: 1,
  },
  {
    id: "layout-fixed-tilt",
    file: "layout/fixed-tilt.png",
    page: "/docs/first-layout",
    title: "A finished fixed-tilt layout",
    alt: "A generated fixed-tilt layout showing the boundary, placed tables, control rooms and the summary table below.",
    what: "The whole window after a successful fixed-tilt run on a single-plot site: the boundary, the placed tables, the control rooms, the legend, and the summary table filled in below the plot.",
    state: "Fixed Tilt + String Inverter, a single-boundary file of roughly 50 to 100 acres, defaults elsewhere. Maximise the window and press Home on the plot toolbar to fit the view.",
    annotations: "Number the boundary 1, a table 2, a control room 3, and the summary table 4.",
    priority: 1,
  },
  {
    id: "layout-tracker",
    file: "layout/tracker.png",
    page: "/docs/design-modes",
    title: "A finished tracker layout",
    alt: "A generated single-axis tracker layout, with the long tracker units running north to south.",
    what: "The plot area after a tracker run on the same site, so the north-south unit orientation contrasts with the fixed-tilt image.",
    state: "Single Axis Tracker + String Inverter on the same file used for the fixed-tilt image. Fit the view.",
    annotations: "Add a north arrow and label the tracker axis direction.",
    priority: 1,
  },
  {
    id: "layout-multi-plot",
    file: "layout/multi-plot.png",
    page: "/docs/layout/multi-plot",
    title: "A multi-plot site",
    alt: "A layout across several separate plant boundaries, each with its own tables and control rooms.",
    what: "The plot area for a file containing three or more separate boundaries, all laid out, with the summary table below showing one row per plant plus the total row.",
    state: "Load a multi-boundary file and generate. Fit the view so every plot is visible.",
    annotations: "Label two plots with their names as they appear in the summary rows.",
    priority: 1,
  },
  {
    id: "toolbar",
    file: "layout/toolbar.png",
    page: "/docs/layout/how-placement-works",
    title: "The plot toolbar",
    alt: "The toolbar above the plot with the save, expand, satellite, wireframe, piles, sketch, bill of materials and diagram buttons.",
    what: "The full toolbar row, wide enough that every button label is readable.",
    state: "After a layout has been generated, so the satellite and piles buttons are enabled.",
    annotations: "",
    priority: 1,
  },
  {
    id: "view-toggles",
    file: "layout/view-toggles.png",
    page: "/docs/layout/cables",
    title: "View switches",
    alt: "The row of on and off switches for cables, terrain, plant layout, legend, arresters and summary.",
    what: "The whole block of switches with each label and its current state readable, at their default states.",
    state: "After a layout has been generated. Do not change any switch first.",
    annotations: "",
    priority: 1,
  },
  {
    id: "layout-satellite",
    file: "layout/satellite.png",
    page: "/docs/layout/how-placement-works",
    title: "Layout over aerial imagery",
    alt: "A layout drawn over an aerial photograph of the real site.",
    what: "The plot with the aerial photograph behind the layout, so the placement can be read against real ground features.",
    state: "Generate a layout, then switch the satellite button on. Needs an internet connection.",
    annotations: "",
    priority: 2,
  },
  {
    id: "layout-wireframe",
    file: "layout/wireframe.png",
    page: "/docs/layout/how-placement-works",
    title: "Outline drawing",
    alt: "The same layout drawn as outlines only, with no colour fill on the tables.",
    what: "The plot with tables drawn as outlines only, ideally at a zoom where individual tables are distinguishable.",
    state: "Generate a layout, then switch wireframe on.",
    annotations: "",
    priority: 2,
  },
  {
    id: "layout-icr-detail",
    file: "layout/icr-detail.png",
    page: "/docs/layout/icr",
    title: "A control room among the tables",
    alt: "A close view of one control room with the surrounding tables cleared from its footprint.",
    what: "A zoomed view of a single control room, showing its label and the gap in the table grid where it sits.",
    state: "Generate a layout, then zoom into one control room.",
    annotations: "Outline the control room and label the cleared gap.",
    priority: 1,
  },
  {
    id: "layout-icr-drag",
    file: "layout/icr-drag.png",
    page: "/docs/layout/icr",
    title: "Dragging a control room",
    alt: "A control room mid-drag, being moved to a new position on the plot.",
    what: "The moment during a drag when the control room has left its original position — the cursor and the room's new position both visible.",
    state: "With no pan or zoom tool active, click and hold a control room and drag it. Capture during the drag.",
    annotations: "Arrow from the original position to the new one.",
    priority: 2,
  },
  {
    id: "layout-arresters",
    file: "layout/arresters.png",
    page: "/docs/layout/lightning-arresters",
    title: "Lightning arresters and their coverage",
    alt: "A layout with lightning arresters placed on a grid, each with its circular protection area drawn.",
    what: "The plot with arresters visible, their protection circles drawn, and the overlap between neighbouring circles clear.",
    state: "Tick the arrester option, generate, then switch the arrester display on.",
    annotations: "Outline one arrester rectangle and one protection circle; mark where two circles overlap.",
    priority: 1,
  },
  {
    id: "layout-arresters-sat",
    file: "layout/arresters-sat.png",
    page: "/docs/layout/lightning-arresters",
    title: "Arresters on a tracker plant",
    alt: "A tracker layout with small arrester markers sitting in the gaps between tracker columns.",
    what: "A zoomed tracker view showing the small square arrester markers positioned in the gaps between tracker columns, with no tracker units removed.",
    state: "A tracker mode with arresters enabled. Zoom in far enough that the markers are visible.",
    annotations: "Outline one marker and label the inter-row gap it sits in.",
    priority: 2,
  },
  {
    id: "layout-street-lights",
    file: "layout/street-lights.png",
    page: "/docs/layout/site-equipment",
    title: "Perimeter street lights",
    alt: "A layout with street light poles spaced along the inside of the plant perimeter.",
    what: "The plot with street lights placed, zoomed enough along one edge that the even pole spacing inside the fence is visible.",
    state: "Switch street lights on, then generate. Zoom to one boundary edge.",
    annotations: "Mark the pole-to-pole span with a dimension line.",
    priority: 2,
  },
  {
    id: "layout-mcr-placed",
    file: "layout/mcr-placed.png",
    page: "/docs/layout/site-equipment",
    title: "Main control room placed",
    alt: "A layout with the main control room placed and the status line reporting the total medium-voltage cable length.",
    what: "The plot with the main control room visible, plus the hint line below the placement buttons reporting the total medium-voltage cable length.",
    state: "Generate a layout with cable calculation on, click Place MCR, then click a position inside the boundary.",
    annotations: "Outline the main control room and the hint line.",
    priority: 1,
  },
  {
    id: "layout-uss-multiplot",
    file: "layout/uss-multiplot.png",
    page: "/docs/layout/multi-plot",
    title: "Unit substations across plots",
    alt: "A multi-plot layout where one plot holds the main control room and each other plot holds a unit substation.",
    what: "A multi-plot layout after placing the main control room: one plot carries the main control room, every other plot carries a unit substation.",
    state: "Load a multi-boundary file, generate, then Place MCR in one plot.",
    annotations: "Label the main control room and two unit substations.",
    priority: 2,
  },
  {
    id: "layout-obstructions",
    file: "layout/obstructions.png",
    page: "/docs/layout/obstructions",
    title: "Obstructions clearing tables",
    alt: "A layout with water bodies, a transmission line corridor and a hand-drawn obstruction, each with the tables cleared around them.",
    what: "The plot showing several kinds of excluded area at once — a water body, a transmission line corridor, and a hand-drawn obstruction — with tables absent from all of them.",
    state: "Use a file containing a water polygon and a transmission line, generate, then draw one rectangular obstruction in Sketch Mode.",
    annotations: "Label each excluded area with its kind.",
    priority: 1,
  },
  {
    id: "obstruction-controls",
    file: "layout/obstruction-controls.png",
    page: "/docs/layout/obstructions",
    title: "Obstruction drawing controls",
    alt: "The obstruction controls with buttons to draw a rectangle or polygon, undo the last one and clear all.",
    what: "The obstruction control group with all four buttons and the hint line below them.",
    state: "After a layout has been generated. Arm the rectangle tool so the hint text is showing.",
    annotations: "",
    priority: 2,
  },
  {
    id: "layout-terrain",
    file: "layout/terrain.png",
    page: "/docs/inputs/topography",
    title: "Terrain contours and excluded ground",
    alt: "A layout on sloping ground with elevation contours drawn and the steep areas excluded from placement.",
    what: "The plot with terrain enabled on a genuinely sloping site: the coloured contour lines and the excluded areas, with no tables on the excluded ground.",
    state: "Pick a site with real relief, switch terrain on, generate, then switch the terrain display on.",
    annotations: "Label one excluded area and point out the contour colour ramp.",
    priority: 1,
  },
  {
    id: "layout-cables-dc-ac",
    file: "layout/cables-dc-ac.png",
    page: "/docs/layout/cables",
    title: "String and feeder cable routing",
    alt: "A layout with direct-current string cables and alternating-current feeder cables both drawn.",
    what: "A zoomed view with both cable types switched on, close enough that the right-angled routing and the inverter positions are clear.",
    state: "Generate with cable calculation on, then switch both cable displays on and zoom into one block.",
    annotations: "Label one string cable, one feeder cable and one inverter.",
    priority: 1,
  },
  {
    id: "layout-cables-mv",
    file: "layout/cables-mv.png",
    page: "/docs/layout/cables",
    title: "Medium-voltage cables sharing a trunk",
    alt: "Medium-voltage cables running from several control rooms and merging into a shared trunk toward the main control room.",
    what: "The plot with the medium-voltage display on, showing several control rooms' cables merging into a shared trunk rather than running in parallel.",
    state: "Generate with cable calculation on, place the main control room, then switch the medium-voltage display on.",
    annotations: "Mark a junction where two routes merge.",
    priority: 1,
  },
  {
    id: "summary-table",
    file: "layout/summary-table.png",
    page: "/docs/reference/summary-columns",
    title: "Layout and energy summary",
    alt: "The summary table below the plot, with one row per plant and a total row.",
    what: "The summary table after a multi-plot run with energy calculated, scrolled to show as many columns as possible, with the total row visible.",
    state: "Generate a multi-plot layout with cable calculation on, then calculate energy.",
    annotations: "",
    priority: 1,
  },
  {
    id: "summary-table-maximized",
    file: "layout/summary-maximized.png",
    page: "/docs/reference/summary-columns",
    title: "Summary in its own window",
    alt: "The summary table opened in a large separate window so every column is readable.",
    what: "The maximised summary window with the full column set readable.",
    state: "Click Maximize on the summary header.",
    annotations: "",
    priority: 1,
  },
  {
    id: "expand-plot",
    file: "layout/expand-plot.png",
    page: "/docs/layout/how-placement-works",
    title: "Expanded plot view",
    alt: "The plot opened in a large window with a button to return to the main window.",
    what: "The expanded plot window with the return button visible.",
    state: "Click Expand Plot on the toolbar.",
    annotations: "Outline the return button.",
    priority: 2,
  },

  // ── Sketch mode and piles ─────────────────────────────────────────────
  {
    id: "sketch-palette",
    file: "editing/sketch-palette.png",
    page: "/docs/editing/sketch-mode",
    title: "The sketch tool palette",
    alt: "The sketch mode tool palette showing every drawing and editing tool.",
    what: "The full palette with every tool button label readable, including the snap, orthogonal, grid, undo and redo controls and the layer row.",
    state: "Generate a layout, then switch Sketch Mode on. Capture the palette area of the panel; stitch if it does not fit.",
    annotations: "Group the buttons and label the groups: select and edit, place, draw, annotate, trenches, navigate.",
    priority: 1,
  },
  {
    id: "sketch-selection",
    file: "editing/sketch-selection.png",
    page: "/docs/editing/sketch-mode",
    title: "Selecting several tables",
    alt: "Several tables highlighted as a selection after a rubber-band drag.",
    what: "A zoomed plot view with a group of tables highlighted in the selection colour, ideally mid rubber-band so the selection rectangle is visible too.",
    state: "In Sketch Mode with the move tool active, drag on empty space across a group of tables.",
    annotations: "Outline the rubber-band rectangle.",
    priority: 1,
  },
  {
    id: "sketch-measure",
    file: "editing/sketch-measure.png",
    page: "/docs/editing/annotations",
    title: "Measuring a distance",
    alt: "A measurement drawn across the plot showing a distance and bearing.",
    what: "A measurement between two points with the distance and bearing readout visible.",
    state: "In Sketch Mode, pick the measure tool and click two points.",
    annotations: "",
    priority: 2,
  },
  {
    id: "sketch-dimension",
    file: "editing/sketch-dimension.png",
    page: "/docs/editing/annotations",
    title: "A dimension annotation",
    alt: "A dimension annotation placed between two points on the layout.",
    what: "A dimension with its extension lines and value, placed against something recognisable such as a row pitch.",
    state: "In Sketch Mode, pick the dimension tool and drag between two points.",
    annotations: "",
    priority: 2,
  },
  {
    id: "sketch-trench",
    file: "editing/sketch-trench.png",
    page: "/docs/layout/cables",
    title: "A hand-drawn cable trench",
    alt: "A hand-drawn trench route on the layout alongside the automatically routed cables.",
    what: "A zoomed view with one hand-drawn trench visible in its own colour, next to automatically routed cables for contrast.",
    state: "Generate with cable calculation on, then in Sketch Mode use a trench tool to draw a route.",
    annotations: "Label the hand-drawn trench and one automatic route.",
    priority: 2,
  },
  {
    id: "sketch-annotations",
    file: "editing/sketch-annotations.png",
    page: "/docs/editing/annotations",
    title: "Annotations, scale bar and north arrow",
    alt: "A layout with text labels, drawn shapes, a scale bar and a north arrow added.",
    what: "The plot carrying several kinds of annotation at once — a text label, a drawn shape, and the scale bar and north arrow.",
    state: "In Sketch Mode add a text label and a shape, then click the scale bar and north button.",
    annotations: "",
    priority: 2,
  },
  {
    id: "pile-dialog",
    file: "editing/pile-dialog.png",
    page: "/docs/editing/piles",
    title: "Pile layout editor",
    alt: "The pile layout editor showing one reference table with piles placed on it and the coordinate table beside it.",
    what: "The editor with several piles placed on the reference table, the drawing on one side and the coordinate table on the other.",
    state: "Generate a layout, then switch the piles button on for the first time, or use Edit-Pile ▸ Define Pile Layout…",
    annotations: "Mark the table's bottom-left corner as the origin and label the two axis directions.",
    priority: 1,
  },
  {
    id: "piles-overlay",
    file: "editing/piles-overlay.png",
    page: "/docs/editing/piles",
    title: "Piles across the plant",
    alt: "A zoomed layout view with the pile pattern repeated on every table.",
    what: "A zoomed plot view with the pile overlay on, showing the same pattern stamped on several neighbouring tables.",
    state: "Define a pile pattern, then keep the piles button on and zoom into a block of tables.",
    annotations: "",
    priority: 1,
  },

  // ── Energy results ─────────────────────────────────────────────────────
  {
    id: "energy-buttons",
    file: "energy/buttons.png",
    page: "/docs/energy/overview",
    title: "Energy controls",
    alt: "The Calculate Energy, Show Energy Chart and Export controls with the interval selector.",
    what: "The energy button block: Calculate Energy, Show Energy Chart, the export button and its interval selector, plus the status line.",
    state: "After a layout has been generated, so the buttons are enabled.",
    annotations: "",
    priority: 1,
  },
  {
    id: "energy-summary-columns",
    file: "energy/summary-columns.png",
    page: "/docs/energy/overview",
    title: "Energy results in the summary",
    alt: "The right-hand end of the summary table showing the probability, capacity factor and lifetime energy columns.",
    what: "The summary table scrolled to its right-hand end so the three probability columns, the capacity factor and the lifetime energy column are all readable.",
    state: "Generate a layout, calculate energy, then scroll the summary table right — or use the maximised window.",
    annotations: "Label the three probability columns.",
    priority: 1,
  },
  {
    id: "energy-chart-daily",
    file: "energy/chart-daily.png",
    page: "/docs/energy/timeseries",
    title: "Daily energy and irradiance",
    alt: "The daily chart with hourly energy bars above hourly irradiance bars, a day slider and a crosshair readout.",
    what: "The daily view with both charts drawn, the day slider visible, and the crosshair active so the readout strip shows values.",
    state: "Calculate energy, click Show Energy Chart, and hover the pointer over the middle of the day.",
    annotations: "Label the two charts and the day slider.",
    priority: 1,
  },
  {
    id: "energy-chart-monthly",
    file: "energy/chart-monthly.png",
    page: "/docs/energy/timeseries",
    title: "Monthly energy and irradiance",
    alt: "The monthly chart with twelve energy bars and twelve irradiance bars, plus the annual totals.",
    what: "The monthly view with all twelve months and the annual totals visible.",
    state: "In the energy chart window, switch to the monthly view.",
    annotations: "",
    priority: 1,
  },
  {
    id: "shadow-view",
    file: "energy/shadow-view.png",
    page: "/docs/energy/shading",
    title: "Shadow view",
    alt: "A side-view cross-section of three rows showing where the front row's shadow falls on the row behind, with day and time sliders.",
    what: "The shadow view with three rows drawn, a shadow clearly falling on the row behind, and both sliders visible with their current day and hour.",
    state: "Generate a layout, click Shadow View, then move the day slider to midwinter and the hour slider to early morning so a shadow is actually cast.",
    annotations: "Label the shaded part of the rear row and both sliders.",
    priority: 1,
  },

  // ── Simulation ─────────────────────────────────────────────────────────
  {
    id: "ac-capacity-dialog",
    file: "simulation/ac-capacity-dialog.png",
    page: "/docs/simulation/ac-capacity",
    title: "Sizing from an alternating-current capacity",
    alt: "The capacity simulation window with a target capacity, a target ratio and the resulting figures.",
    what: "The window with a target capacity and ratio entered and the computed results showing, including the resulting module and inverter counts.",
    state: "Generate a layout, load a module file and an inverter file, then click the capacity simulation button.",
    annotations: "Outline the two inputs and the computed target.",
    priority: 1,
  },
  {
    id: "ac-capacity-regenerate",
    file: "simulation/ac-capacity-regenerate.png",
    page: "/docs/simulation/ac-capacity",
    title: "Offer to cap the layout",
    alt: "The prompt offering to regenerate the layout capped to the target capacity.",
    what: "The prompt shown when the target is reachable, offering to regenerate the layout capped to it.",
    state: "Run the capacity simulation with a target below the first run's capacity.",
    annotations: "",
    priority: 2,
  },
  {
    id: "robotic-cleaning-dialog",
    file: "simulation/robotic-cleaning-dialog.png",
    page: "/docs/simulation/robotic-cleaning",
    title: "Cleaning robot sizing",
    alt: "The robotic cleaning window with the robot inputs, the list of wide gaps with their tick boxes, and the resulting fleet size.",
    what: "The window with the battery and bridge inputs at the top, both gap lists populated — gaps blocked by equipment and gaps in open ground — and the resulting fleet size.",
    state: "Generate a layout on a site with arresters, control rooms or obstructions so there are wide gaps to list, then click the robotic cleaning button.",
    annotations: "Label the two gap groups and the fleet result.",
    priority: 1,
  },
  {
    id: "robotic-cleaning-overlay",
    file: "simulation/robotic-cleaning-overlay.png",
    page: "/docs/simulation/robotic-cleaning",
    title: "Bridged gaps on the plot",
    alt: "A layout with a bridged gap highlighted between two runs of tables.",
    what: "A zoomed plot view where a ticked gap is highlighted, showing where a supported bridge would be installed.",
    state: "In the robotic cleaning window, tick one wide gap and preview it, then zoom to that location.",
    annotations: "Outline the highlighted bridge area.",
    priority: 2,
  },

  // ── Single-line diagram ────────────────────────────────────────────────
  {
    id: "sld-mode",
    file: "sld/mode.png",
    page: "/docs/sld/overview",
    title: "Diagram mode",
    alt: "The diagram editor with the drawing sheet frame, its title block and the symbol palette.",
    what: "The whole window in diagram mode: the sheet frame with its border, zone grid and right-hand legend and title-block band, plus the symbol palette.",
    state: "Generate a layout, then switch the diagram button on.",
    annotations: "Label the sheet border, the zone grid, the legend band and the title block.",
    priority: 1,
  },
  {
    id: "sld-palette",
    file: "sld/palette.png",
    page: "/docs/sld/symbols",
    title: "The symbol palette",
    alt: "The diagram symbol palette listing the available equipment and switchgear symbols.",
    what: "The full palette with every symbol button label readable. Stitch if it does not fit in one frame.",
    state: "In diagram mode, capture the palette area of the panel.",
    annotations: "",
    priority: 1,
  },
  {
    id: "sld-autobuild",
    file: "sld/autobuild.png",
    page: "/docs/sld/auto-build",
    title: "An automatically built diagram",
    alt: "A diagram generated from the plant, showing the equipment chain annotated with quantities and ratings.",
    what: "The sheet after auto-build on a plant with several control rooms, so the chain is annotated with real quantities and ratings.",
    state: "Generate a layout, calculate energy so ratings are available, switch to diagram mode and use auto-build.",
    annotations: "Label two blocks with their quantity annotation.",
    priority: 1,
  },
  {
    id: "sld-import-background",
    file: "sld/import-background.png",
    page: "/docs/sld/import-and-custom-symbols",
    title: "An imported diagram as a background",
    alt: "An existing diagram imported as a background image with editable symbols drawn on top of it.",
    what: "The sheet with an imported diagram behind it and at least one editable symbol and wire placed on top, so the difference between background and editable content is visible.",
    state: "In diagram mode, import a diagram file, then place one symbol and one wire over it.",
    annotations: "Label the background and the editable symbol.",
    priority: 2,
  },
  {
    id: "sld-symbol-editor",
    file: "sld/symbol-editor.png",
    page: "/docs/sld/import-and-custom-symbols",
    title: "Symbol editor",
    alt: "The symbol editor showing strokes traced from an image, with pen, erase and clear tools.",
    what: "The editor with a traced symbol visible and the three editing tools.",
    state: "In diagram mode, import an image symbol. The editor opens automatically.",
    annotations: "",
    priority: 2,
  },

  // ── Bill of materials ─────────────────────────────────────────────────
  {
    id: "bom-mode",
    file: "bom/mode.png",
    page: "/docs/bom/overview",
    title: "Bill of materials mode",
    alt: "The bill of materials editor with its five columns filled from the layout, and the row and export controls.",
    what: "The editor with the automatically computed rows filled in, all five column headers readable, and the add, delete, rebuild and export controls visible.",
    state: "Generate a layout, then switch the bill of materials button on.",
    annotations: "",
    priority: 1,
  },
  {
    id: "bom-template-window",
    file: "bom/template-window.png",
    page: "/docs/bom/templates",
    title: "A template beside the plant list",
    alt: "A template opened in its own window next to the automatically computed bill of materials.",
    what: "Both windows visible at once: the template in its own window and the automatic list behind it, so the side-by-side relationship is clear.",
    state: "In bill of materials mode, pick a template and load it. Arrange the two windows so both are readable.",
    annotations: "Label which window is the template and which is the plant list.",
    priority: 1,
  },

  // ── Exports ────────────────────────────────────────────────────────────
  {
    id: "export-buttons",
    file: "exports/buttons.png",
    page: "/docs/exports/pdf-report",
    title: "Export controls",
    alt: "The export buttons for the report, the pile report, the mapping file and the drawing file.",
    what: "The export button block with every button label readable.",
    state: "After a layout has been generated, so the buttons are enabled.",
    annotations: "",
    priority: 1,
  },
  {
    id: "pdf-page-drawing",
    file: "exports/pdf-page-drawing.png",
    page: "/docs/exports/pdf-report",
    title: "Report page one — the drawing",
    alt: "The first page of the exported report: the layout drawing with a border, north arrow, title block and plant details table.",
    what: "The whole first page of an exported report, at a zoom where the title block and the plant details table are legible.",
    state: "Export a report, then open page one in a reader at a page-fit zoom.",
    annotations: "Label the north arrow, the title block and the plant details table.",
    priority: 1,
  },
  {
    id: "pdf-page-summary",
    file: "exports/pdf-page-summary.png",
    page: "/docs/exports/pdf-report",
    title: "Report page two — the summary",
    alt: "The summary page of the exported report with the layout summary, design parameters and cable tables.",
    what: "The whole summary page, legible enough that the table headings can be read.",
    state: "Open page two of the same exported report.",
    annotations: "Label the three table blocks.",
    priority: 1,
  },
  {
    id: "pdf-page-sld",
    file: "exports/pdf-page-sld.png",
    page: "/docs/exports/pdf-report",
    title: "Report diagram page",
    alt: "The single-line diagram page of the exported report on its drawing sheet.",
    what: "The diagram page of the report, showing the diagram on its sheet frame.",
    state: "Build or auto-build a diagram before exporting, then open that page of the report.",
    annotations: "",
    priority: 2,
  },
  {
    id: "pdf-page-bom",
    file: "exports/pdf-page-bom.png",
    page: "/docs/exports/pdf-report",
    title: "Report bill of materials page",
    alt: "A bill of materials page from the exported report.",
    what: "One bill of materials page from the report, legible enough to read the columns.",
    state: "Open the bill of materials page of the same exported report.",
    annotations: "",
    priority: 2,
  },
  {
    id: "pdf-page-energy",
    file: "exports/pdf-page-energy.png",
    page: "/docs/exports/pdf-report",
    title: "Report energy page",
    alt: "The energy page of the exported report with the loss breakdown and the monthly table.",
    what: "An energy page from a report where energy was calculated with monthly data available, so the monthly table and the multi-year forecast appear.",
    state: "Calculate energy with an hourly file or the automatic service before exporting, then open the energy pages.",
    annotations: "",
    priority: 2,
  },
  {
    id: "export-kmz-google-earth",
    file: "exports/kmz-google-earth.png",
    page: "/docs/exports/kmz",
    title: "An exported mapping file in Google Earth",
    alt: "An exported layout opened in Google Earth, with the folder tree showing one folder per plant and a summary placemark.",
    what: "Google Earth with the exported file open, the Places tree expanded to show the per-plant folders and the summary folder, and the layout drawn over the imagery.",
    state: "Export the mapping file, then open it in Google Earth Pro and expand the tree.",
    annotations: "Label the per-plant folder and the summary placemark.",
    priority: 1,
  },
  {
    id: "export-kmz-summary-placemark",
    file: "exports/kmz-summary-placemark.png",
    page: "/docs/exports/kmz",
    title: "The summary placemark",
    alt: "The summary placemark balloon in Google Earth showing capacity, area, pitch and table count.",
    what: "The balloon that opens when the summary placemark is clicked, showing its figures.",
    state: "In Google Earth, click the summary placemark.",
    annotations: "",
    priority: 2,
  },
  {
    id: "export-dxf-cad",
    file: "exports/dxf-cad.png",
    page: "/docs/exports/dxf",
    title: "An exported drawing file in a CAD program",
    alt: "An exported drawing opened in a CAD program with the layer list visible.",
    what: "A CAD program with the exported drawing open and the layer panel visible, so the layer names can be read against the drawing.",
    state: "Export the drawing file and open it in AutoCAD or BricsCAD. Show the layer manager.",
    annotations: "Outline the layer list.",
    priority: 1,
  },

  // ── Projects, menus, errors ───────────────────────────────────────────
  {
    id: "file-menu",
    file: "projects/file-menu.png",
    page: "/docs/projects",
    title: "The File menu",
    alt: "The File menu open, showing new project, mode switching, save, open and exit.",
    what: "The File menu open with every item readable.",
    state: "Click File in the menu bar.",
    annotations: "",
    priority: 1,
  },
  {
    id: "save-project",
    file: "projects/save-project.png",
    page: "/docs/projects",
    title: "Saving a project",
    alt: "The save dialog with the project file type selected.",
    what: "The save dialog showing the project file extension in the file type row.",
    state: "Use File ▸ Save Project… after generating a layout.",
    annotations: "Outline the file type row.",
    priority: 2,
  },
  {
    id: "help-menu",
    file: "projects/help-menu.png",
    page: "/docs/support",
    title: "The Help menu",
    alt: "The Help menu open, showing the usage guide and the licence window.",
    what: "The Help menu open with both items readable.",
    state: "Click Help in the menu bar.",
    annotations: "",
    priority: 2,
  },
  {
    id: "f1-help",
    file: "projects/f1-help.png",
    page: "/docs/support",
    title: "The in-app guide",
    alt: "The in-app guide open on its first tab, with the tab strip visible.",
    what: "The guide window with its tab strip fully visible.",
    state: "Press F1, or use Help ▸ How to Use This Tool.",
    annotations: "",
    priority: 2,
  },
  {
    id: "unexpected-error",
    file: "projects/unexpected-error.png",
    page: "/docs/troubleshooting",
    title: "The unexpected error message",
    alt: "The message shown after an unexpected error, stating that the application will keep running.",
    what: "The message exactly as it appears, so a reader can match what they are seeing.",
    state: "Capture opportunistically if one occurs — do not force an error to get this.",
    annotations: "",
    priority: 3,
  },
]

/** Lookup used by `<Screenshot id="…" />`. */
export const SCREENSHOTS_BY_ID: Record<string, ScreenshotSpec> =
  Object.fromEntries(SCREENSHOTS.map((s) => [s.id, s]))
