/**
 * SolarLayout Rooftop screenshot manifest, the twin of `content/bess/screenshots.ts` (same `ScreenshotSpec` shape).
 * Rooftop runs in the browser, so its images are taken with Playwright from rooftop.solarlayout.app at a device scale
 * of 2 (`.claude/skills/update-docs/references/rooftop.md`, "Screenshots"). Ids are always `rooftop-`-prefixed.
 */
import type { ScreenshotSpec } from "@/content/screenshots"

export const SCREENSHOTS: ScreenshotSpec[] = [
  {
    id: "rooftop-home",
    file: "rooftop/home/desktop.png",
    page: "/docs/rooftop/getting-started",
    title: "Home",
    alt: "Rooftop's Home: the headline Find your roof, the search with Find my roof, Import a drawing, Open a project and the demo's card.",
    what: "Home at 1440 × 900 with nothing kept on this device.",
    state: "Open rooftop.solarlayout.app in a fresh browser profile.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-studio-desktop",
    file: "rooftop/studio/array-desktop.png",
    page: "/docs/rooftop/workspace",
    title: "The Studio on a computer",
    alt: "The Studio's Array lens on a computer: the top bar, the lens rail at the left, the demo roof in 3D, the figures under it and the lens's settings at the right.",
    what: "The demo in the Array lens at 1440 × 900, its run landed.",
    state: "Fresh profile: Home, Open the demo, then the Array lens; wait until the figures show numbers.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-studio-phone",
    file: "rooftop/studio/array-phone.png",
    page: "/docs/rooftop/workspace",
    title: "The Studio on a phone",
    alt: "The Studio's Array lens on a phone: the roof in 3D above, the bottom sheet at half height with its lens switch, and the tab bar.",
    what: "The demo in the Array lens at 390 × 844 with touch, its run landed.",
    state: "Fresh profile on a phone-sized window: Home, Open the demo, then the Array lens; wait until the figures show numbers.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-home-designs",
    file: "rooftop/home/designs-desktop.png",
    page: "/docs/rooftop/projects",
    title: "Designs on this device",
    alt: "Home's On this device section with two design cards, the demo and its copy, each with its plan, roof, capacity and energy.",
    what: "Home at 1440 × 900 scrolled to On this device, with two designs kept.",
    state: "Open the demo, let it run, make one edit (the system voltage to 1000 V and back), then Duplicate it from its card's Menu; back on Home.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-find-outline",
    file: "rooftop/walk/outlined.jpg",
    page: "/docs/rooftop/find",
    title: "Find with the roof outlined",
    alt: "Find on the satellite map: a roof outlined by its four corners with a stair room on it, the toolbar of obstacles, and the panel with its edges, area, faces, obstacles and roof type.",
    what: "Find at 1440 × 900 with a closed outline and one box.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-start-here",
    file: "rooftop/find/start-here.jpg",
    page: "/docs/rooftop/find",
    title: "Start here",
    alt: "Find's first step: Search for the building, Use my location, Enter dimensions by hand.",
    what: "The Start here cards of Find's first panel.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-search",
    file: "rooftop/find/search.jpg",
    page: "/docs/rooftop/find",
    title: "The search's places",
    alt: "The search with an area name typed and three places offered, each with its kind.",
    what: "The search field with its list of places.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-find-corners",
    file: "rooftop/find/corners.jpg",
    page: "/docs/rooftop/find",
    title: "An outline closed by its corners",
    alt: "A closed outline of four corners, each edge with its length and a dot in its middle to add a corner.",
    what: "The Corners tool after closing the outline.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-detect",
    file: "rooftop/find/detect.jpg",
    page: "/docs/rooftop/find",
    title: "A footprint proposed",
    alt: "A detected footprint proposed as the outline, with the callout Footprint found, its corners and area, Use this outline and Adjust.",
    what: "Detect building, after a press inside a building with a known footprint.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-move-roof",
    file: "rooftop/find/move-roof.jpg",
    page: "/docs/rooftop/find",
    title: "The roof picked up and turned",
    alt: "The roof picked up, turned by its round handle, with the angle and the direction it faces, and a dashed line where it stood.",
    what: "Box in hand, the roof pressed and its handle dragged.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-find-height",
    file: "rooftop/find/height.jpg",
    page: "/docs/rooftop/find",
    title: "The height of an obstacle",
    alt: "The dialog Height of the box: Name and Height, Remove and Add the box.",
    what: "A box just drawn on the roof.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-building",
    file: "rooftop/find/building.jpg",
    page: "/docs/rooftop/find",
    title: "A building beside the roof",
    alt: "An outlined roof with its obstacles labelled with their heights, and a building beside it.",
    what: "The Building tool, after closing a building beside the roof.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-walk-home",
    file: "rooftop/walk/home.jpg",
    page: "/docs/rooftop/first-design",
    title: "Coordinates on Home",
    alt: "Home with coordinates typed in the search, read back under it and marked Coordinates.",
    what: "Home with 18.5891, 73.7066 typed.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-find",
    file: "rooftop/walk/find.jpg",
    page: "/docs/rooftop/first-design",
    title: "Corners on the roof",
    alt: "Find at the place, four corners of a flat roof placed, the outline still open.",
    what: "Find, Corners in hand, four corners placed.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-height",
    file: "rooftop/walk/height.jpg",
    page: "/docs/rooftop/first-design",
    title: "The stair room's height",
    alt: "The height dialog over the map, the name Stair room and a height of 2.5 m.",
    what: "A box drawn on the roof, its name and height typed.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-outlined",
    file: "rooftop/walk/outlined.jpg",
    page: "/docs/rooftop/first-design",
    title: "The roof outlined",
    alt: "The roof outlined with its stair room, and Build this roof ready.",
    what: "After Add the box.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-roof",
    file: "rooftop/walk/roof.jpg",
    page: "/docs/rooftop/first-design",
    title: "The Roof lens",
    alt: "The Studio's Roof lens after Build: the roof in 3D with its modules, the figures under it, and the roof's settings at the right.",
    what: "The Studio just after Build this roof.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-array",
    file: "rooftop/walk/array.jpg",
    page: "/docs/rooftop/first-design",
    title: "The Array lens",
    alt: "The Array lens: the module, the mounting and the spacing, with the rows on the roof.",
    what: "The Array lens of the new design.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-sun",
    file: "rooftop/walk/sun.jpg",
    page: "/docs/rooftop/first-design",
    title: "The Sun lens",
    alt: "The Sun lens: the sun's path over the roof on the design day, the shadows at the hour, and the day's settings.",
    what: "The Sun lens of the new design.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-strings",
    file: "rooftop/walk/strings.jpg",
    page: "/docs/rooftop/first-design",
    title: "The Strings lens",
    alt: "The Strings lens: the strings in colour on the roof, the inverter, the system voltage set for India, the series range and the options.",
    what: "The Strings lens of the new design.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-performance",
    file: "rooftop/walk/performance.jpg",
    page: "/docs/rooftop/first-design",
    title: "Performance",
    alt: "Performance: the energy of year 1, the figures, the chain from sunlight to the grid, and the energy by month.",
    what: "Performance of the new design, on PVGIS weather.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-handover",
    file: "rooftop/walk/handover.jpg",
    page: "/docs/rooftop/first-design",
    title: "Handover",
    alt: "Handover: the list of what the design hands over, and the design report's preview.",
    what: "Handover of the new design.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
]

/** Lookup used by `<Screenshot id="…" />`. */
export const SCREENSHOTS_BY_ID: Record<string, ScreenshotSpec> =
  Object.fromEntries(SCREENSHOTS.map((s) => [s.id, s]))
