/**
 * SolarLayout Rooftop screenshot manifest, the twin of `content/bess/screenshots.ts` (same `ScreenshotSpec` shape).
 * Rooftop runs in the browser, so its images are taken with Playwright from rooftop.solarlayout.app at a device scale
 * of 2 (`.claude/skills/update-docs/references/rooftop.md`, "Screenshots"). Ids are always `rooftop-`-prefixed.
 */
import type { ScreenshotSpec } from "@/content/screenshots"

export const SCREENSHOTS: ScreenshotSpec[] = [
  {
    id: "rooftop-home",
    file: "rooftop/home/desktop.png",
    page: "/docs/rooftop/getting-started",
    title: "Home",
    alt: "Rooftop's Home: the headline Find your roof, the search with Find my roof, Import a drawing, Open a project and the demo's card.",
    what: "Home at 1440 × 900 with nothing kept on this device.",
    state: "Open rooftop.solarlayout.app in a fresh browser profile.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-studio-desktop",
    file: "rooftop/studio/array-desktop.png",
    page: "/docs/rooftop/workspace",
    title: "The Studio on a computer",
    alt: "The Studio's Array lens on a computer: the top bar, the lens rail at the left, the demo roof in 3D, the figures under it and the lens's settings at the right.",
    what: "The demo in the Array lens at 1440 × 900, its run landed.",
    state: "Fresh profile: Home, Open the demo, then the Array lens; wait until the figures show numbers.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-studio-phone",
    file: "rooftop/studio/array-phone.png",
    page: "/docs/rooftop/workspace",
    title: "The Studio on a phone",
    alt: "The Studio's Array lens on a phone: the roof in 3D above, the bottom sheet at half height with its lens switch, and the tab bar.",
    what: "The demo in the Array lens at 390 × 844 with touch, its run landed.",
    state: "Fresh profile on a phone-sized window: Home, Open the demo, then the Array lens; wait until the figures show numbers.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-home-designs",
    file: "rooftop/home/designs-desktop.png",
    page: "/docs/rooftop/projects",
    title: "Designs on this device",
    alt: "Home's On this device section with two design cards, the demo and its copy, each with its plan, roof, capacity and energy.",
    what: "Home at 1440 × 900 scrolled to On this device, with two designs kept.",
    state: "Open the demo, let it run, make one edit (the system voltage to 1000 V and back), then Duplicate it from its card's Menu; back on Home.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-find-outline",
    file: "rooftop/walk/outlined.jpg",
    page: "/docs/rooftop/find",
    title: "Find with the roof outlined",
    alt: "Find on the satellite map: a roof outlined by its four corners with a stair room on it, the toolbar of obstacles, and the panel with its edges, area, faces, obstacles and roof type.",
    what: "Find at 1440 × 900 with a closed outline and one box.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-start-here",
    file: "rooftop/find/start-here.jpg",
    page: "/docs/rooftop/find",
    title: "Start here",
    alt: "Find's first step: Search for the building, Use my location, Enter dimensions by hand.",
    what: "The Start here cards of Find's first panel.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-search",
    file: "rooftop/find/search.jpg",
    page: "/docs/rooftop/find",
    title: "The search's places",
    alt: "The search with an area name typed and three places offered, each with its kind.",
    what: "The search field with its list of places.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-find-corners",
    file: "rooftop/find/corners.jpg",
    page: "/docs/rooftop/find",
    title: "An outline closed by its corners",
    alt: "A closed outline of four corners, each edge with its length and a dot in its middle to add a corner.",
    what: "The Corners tool after closing the outline.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-detect",
    file: "rooftop/find/detect.jpg",
    page: "/docs/rooftop/find",
    title: "A footprint proposed",
    alt: "A detected footprint proposed as the outline, with the callout Footprint found, its corners and area, and Use this outline.",
    what: "Detect building, after a press inside a building with a known footprint.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-move-roof",
    file: "rooftop/find/move-roof.jpg",
    page: "/docs/rooftop/find",
    title: "The roof picked up and turned",
    alt: "The roof picked up, turned by its round handle, with the angle and the direction it faces, and a dashed line where it stood.",
    what: "Box in hand, the roof pressed and its handle dragged.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-find-height",
    file: "rooftop/find/height.jpg",
    page: "/docs/rooftop/find",
    title: "The height of an obstacle",
    alt: "The dialog Height of the box: Name and Height, Remove and Add the box.",
    what: "A box just drawn on the roof.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-find-building",
    file: "rooftop/find/building.jpg",
    page: "/docs/rooftop/find",
    title: "A building beside the roof",
    alt: "An outlined roof with its obstacles labelled with their heights, and a building beside it.",
    what: "The Building tool, after closing a building beside the roof.",
    state: "Taken from the app's own help picture of this how-to (rooftop-design-app apps/web/public/help/find), the map without imagery.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-walk-home",
    file: "rooftop/walk/home.jpg",
    page: "/docs/rooftop/first-design",
    title: "Coordinates on Home",
    alt: "Home with coordinates typed in the search, read back under it and marked Coordinates.",
    what: "Home with 18.5891, 73.7066 typed.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-find",
    file: "rooftop/walk/find.jpg",
    page: "/docs/rooftop/first-design",
    title: "Corners on the roof",
    alt: "Find at the place, four corners of a flat roof placed, the outline still open.",
    what: "Find, Corners in hand, four corners placed.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-height",
    file: "rooftop/walk/height.jpg",
    page: "/docs/rooftop/first-design",
    title: "The stair room's height",
    alt: "The height dialog over the map, the name Stair room and a height of 2.5 m.",
    what: "A box drawn on the roof, its name and height typed.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-outlined",
    file: "rooftop/walk/outlined.jpg",
    page: "/docs/rooftop/first-design",
    title: "The roof outlined",
    alt: "The roof outlined with its stair room, and Build this roof ready.",
    what: "After Add the box.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-roof",
    file: "rooftop/walk/roof.jpg",
    page: "/docs/rooftop/first-design",
    title: "The Roof lens",
    alt: "The Studio's Roof lens after Build: the roof in 3D with its modules, the figures under it, and the roof's settings at the right.",
    what: "The Studio just after Build this roof.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-array",
    file: "rooftop/walk/array.jpg",
    page: "/docs/rooftop/first-design",
    title: "The Array lens",
    alt: "The Array lens: the module, the mounting and the spacing, with the rows on the roof.",
    what: "The Array lens of the new design.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-sun",
    file: "rooftop/walk/sun.jpg",
    page: "/docs/rooftop/first-design",
    title: "The Sun lens",
    alt: "The Sun lens: the sun's path over the roof on the design day, the shadows at the hour, and the day's settings.",
    what: "The Sun lens of the new design.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-strings",
    file: "rooftop/walk/strings.jpg",
    page: "/docs/rooftop/first-design",
    title: "The Strings lens",
    alt: "The Strings lens: the strings in colour on the roof, the inverter, the system voltage set for India, the series range and the options.",
    what: "The Strings lens of the new design.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-performance",
    file: "rooftop/walk/performance.jpg",
    page: "/docs/rooftop/first-design",
    title: "Performance",
    alt: "Performance: the energy of year 1, the figures, the chain from sunlight to the grid, and the energy by month.",
    what: "Performance of the new design, on PVGIS weather.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-walk-handover",
    file: "rooftop/walk/handover.jpg",
    page: "/docs/rooftop/first-design",
    title: "Handover",
    alt: "Handover: the list of what the design hands over, and the design report's preview.",
    what: "Handover of the new design.",
    state: "The walkthrough's run on staging at 1440 × 900: Home, coordinates 18.5891, 73.7066, the roof by its four corners, a box of 2.5 m, Build this roof, then each lens and workspace by the app's own links (a reload would open the demo).",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-roof-lens",
    file: "rooftop/roof/lens.jpg",
    page: "/docs/rooftop/roof",
    title: "The Roof lens",
    alt: "The Roof lens on a computer: the demo roof in 3D, and the inspector with Location, Roof type, Edges and access and Obstacles.",
    what: "The demo in the Roof lens at 1440 × 900.",
    state: "Open the demo, then the Roof lens; wait for the run.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-roof-add",
    file: "rooftop/roof/add.jpg",
    page: "/docs/rooftop/roof",
    title: "Add an obstacle",
    alt: "The Obstacles section with the Add menu open: Box, Tank, Wall, Tree and Building, each with the size a new one gets.",
    what: "The Roof lens, Obstacles, Add pressed.",
    state: "The demo in the Roof lens; press Add under Obstacles.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-roof-review",
    file: "rooftop/roof/review.jpg",
    page: "/docs/rooftop/roof",
    title: "Heights to review",
    alt: "A roof imported from a KML: under Location the note that obstacles had no height and were set to 1.0 m with Review, and the Vent marked for review.",
    what: "The Roof lens just after importing a drawing in which one obstacle has no height.",
    state: "Home, Import a drawing, a KML with a tank named 'Tank h=2.5' and a vent with no height; Open the roof.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-array-lens",
    file: "rooftop/array/lens.jpg",
    page: "/docs/rooftop/array",
    title: "The Array lens",
    alt: "The Array lens on a computer: the module card, Mounting and the start of Spacing beside the demo roof in 3D.",
    what: "The demo in the Array lens at 1440 × 900.",
    state: "Open the demo, then the Array lens; wait for the run.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-array-picker",
    file: "rooftop/array/choose-a-module.jpg",
    page: "/docs/rooftop/array",
    title: "Choose a module",
    alt: "The Choose a module dialog: the search, the Power slider, the list of modules with their power, efficiency, size and bifaciality, one chosen, and a PAN file of your own.",
    what: "Choose a module open from the Array lens, a module chosen in the list.",
    state: "The demo's Array lens, Change on the module card; choose the third module.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-array-window",
    file: "rooftop/array/window.jpg",
    page: "/docs/rooftop/array",
    title: "Spacing and the shade-free window",
    alt: "The Array lens scrolled to Spacing and the Shade-free window: 09:00 to 16:00 on the winter solstice, and Allow shaded positions off.",
    what: "The Array lens, Spacing and Shade-free window in view.",
    state: "The demo's Array lens, scrolled to the Shade-free window.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-sun-lens",
    file: "rooftop/sun/lens.jpg",
    page: "/docs/rooftop/sun",
    title: "The Sun lens",
    alt: "The Sun lens at 10:30 on 21 December: the sun's path over the demo roof with its shade-free part drawn thicker, the shadows, and the Day, Sun at 10:30, Shading over the year and On the roof sections.",
    what: "The demo in the Sun lens at 1440 × 900.",
    state: "Open the demo, then the Sun lens; wait for the run.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-sun-outlines",
    file: "rooftop/sun/outlines.jpg",
    page: "/docs/rooftop/sun",
    title: "Calculated shadow outlines",
    alt: "The Sun lens with Calculated shadow outlines switched on, the engine's shadows drawn over the ones in view.",
    what: "The Sun lens with Calculated shadow outlines on.",
    state: "The demo's Sun lens; switch Calculated shadow outlines on.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-sun-shade-map",
    file: "rooftop/sun/shade-map.jpg",
    page: "/docs/rooftop/sun",
    title: "The shade map",
    alt: "The Shade map tab: every position coloured by its near shading over the year in five steps, the legend with the count of each, and the shading over the year.",
    what: "The Sun lens on its Shade map tab.",
    state: "The demo's Sun lens; choose Shade map.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-strings-lens",
    file: "rooftop/strings/lens.jpg",
    page: "/docs/rooftop/strings",
    title: "The Strings lens",
    alt: "The Strings lens: the strings on the roof coloured by MPPT, the inverter, the system voltage, the modules in series bar and the options A to E.",
    what: "The demo in the Strings lens at 1440 × 900.",
    state: "Open the demo, then the Strings lens; wait for the run.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-strings-series",
    file: "rooftop/strings/series.jpg",
    page: "/docs/rooftop/strings",
    title: "Modules in series",
    alt: "The Modules in series bar from 14, the MPPT minimum, to 29, the Voc limit, the chosen length marked, and the verdict with a tick.",
    what: "The Modules in series section of the demo, cropped from the lens.",
    state: "The demo's Strings lens; the section under System voltage.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-strings-options",
    file: "rooftop/strings/options.jpg",
    page: "/docs/rooftop/strings",
    title: "Options and your own",
    alt: "The options A to E, Recommended first, and Your own added as F and chosen, with Change and Remove.",
    what: "The demo's options with an option of your own added.",
    state: "The demo's Strings lens; Add your own, then Add.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-performance",
    file: "rooftop/performance/page.jpg",
    page: "/docs/rooftop/performance",
    title: "Performance",
    alt: "Performance for the demo: the run line, the Weather and Stringing option controls, Energy to grid with P50, P75 and P90, the figures, the chain from sunlight to the grid and the energy by month.",
    what: "The demo's Performance at 1440 × 900.",
    state: "Open the demo, then Performance; wait for the run.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-performance-csv",
    file: "rooftop/performance/csv.jpg",
    page: "/docs/rooftop/performance",
    title: "A CSV read",
    alt: "The Load weather from a CSV dialog with a year read: 8,760 hours, its irradiation and temperatures, and the notes on irradiance below zero and a gap in the temperature.",
    what: "The CSV dialog after a file is read.",
    state: "Performance, Weather, CSV file; drop a year of hourly weather with two hours below zero and one temperature gap.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-handover",
    file: "rooftop/handover/page.jpg",
    page: "/docs/rooftop/handover",
    title: "Handover",
    alt: "Handover: Download all and the list of what the design hands over at the left, the design report's first page with its thumbnails at the right.",
    what: "The demo's Handover at 1440 × 900, the design report previewed.",
    state: "Open the demo, then Handover.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-handover-sld",
    file: "rooftop/handover/sld.jpg",
    page: "/docs/rooftop/handover",
    title: "The single-line diagram",
    alt: "The single-line diagram preview: the strings of each MPPT in their colours into the inverter, the AC distribution board (ACDB), the meter and the grid, with one MPPT's strings and current shown.",
    what: "Handover, Single-line diagram, one MPPT block pointed at.",
    state: "The demo's Handover; choose Single-line diagram and point at the first MPPT block.",
    annotations: "",
    priority: 2,
  },
  {
    id: "rooftop-present-day",
    file: "rooftop/present/day.jpg",
    page: "/docs/rooftop/present",
    title: "Present, the day",
    alt: "Present during its day scene: the roof in 3D under the sun's path, the scene's panel with the solar time, the sun's height and bearing, and the design's name, capacity and energy at the bottom left.",
    what: "Present about 19 s in, during scene 4.",
    state: "The demo in the Studio; Present; wait about 19 seconds.",
    annotations: "",
    priority: 1,
  },
  {
    id: "rooftop-reference-picker",
    file: "rooftop/reference/choose-a-module.jpg",
    page: "/docs/rooftop/reference",
    title: "The module library",
    alt: "Choose a module: the search, the Power filter, the list with power, efficiency, size and bifaciality, and the strip for a PAN file of your own.",
    what: "Choose a module open from the Array lens.",
    state: "The demo's Array lens, Change on the module card.",
    annotations: "",
    priority: 2,
  },
]

/** Lookup used by `<Screenshot id="…" />`. */
export const SCREENSHOTS_BY_ID: Record<string, ScreenshotSpec> =
  Object.fromEntries(SCREENSHOTS.map((s) => [s.id, s]))
